### PR TITLE
SoundSourceMp3: Fix armv7hl build on gcc 11.1

### PR DESCRIPTION
**Pull request by uklotzde**
https://koji.rpmfusion.org/kojifiles/work/tasks/9616/489616/build.log
```
lib.dir/src/sources/soundsourcemp3.cpp.o -c ../src/sources/soundsourcemp3.cpp
../src/sources/soundsourcemp3.cpp: In member function 'virtual mixxx::ReadableSampleFrames mixxx::SoundSourceMp3::readSampleFramesClamped(const mixxx::WritableSampleFrames&)':
../src/sources/soundsourcemp3.cpp:700:36: error: comparison of integer expressions of different signedness: 'const SINT' {aka 'const int'} and 'mixxx::audio::SampleRate::value_t' {aka 'unsigned int'} [-Werror=sign-compare]
  700 |             if (madSynthSampleRate != getSignalInfo().getSampleRate()) {
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
fix seems analogous to #3997 and I'm assuming that worked, so this should too. Waiting for CI.

**Comment by Holzhaus** [comment]
CI passed.
