### PR TITLE
QML Pt. 3: Add support for retrieving deck track properties

### PR DESCRIPTION
**Pull request by Holzhaus**
This allows displaying  track properties from loaded decks in the QML GUI. Roughly equivalent to `WTrackText`.

Based on #3907.

Minimal working example:

```qml
import Mixxx.CoreServices 1.0 as MixxxCoreServices

Item {
    id: root
    property var deckPlayer: MixxxCoreServices.PlayerManager.getPlayer("[Channel1]")
    
    // Display the track title
    Text {
        text: root.deckPlayer.title
    }
    
    // Display the track color
    Rectangle {
        color: root.deckPlayer.color
    }

    // Change the track title
    Button {
        text: "Change Track Title"
        onClicked: root.deckPlayer.title = "Hello World!"
    }
}
```

Current state of the Demo skin (track on deck 1 has green track color):

Peek 2021-05-25 18-45

### CODE REVIEW

**Comment by uklotzde** [comment]
Wait, wait, let's first merge the prerequisite PRs :sweat_smile:

**Comment by Holzhaus** [comment]
Hmm, that sucks. Apparently `qmlRegisterSingletonInstance` does not exist in older Qt versions. I'll check if we can fall back to some alternative.

**Comment by uklotzde** [comment]
> Hmm, that sucks. Apparently `qmlRegisterSingletonInstance` does not exist in older Qt versions. I'll check if we can fall back to some alternative.

Instead of wasting time with workarounds for outdated Qt versions I suggest to restrict QML support to Qt 5.15 and newer. Can we organize the code in a way that allows to exclude the QML components at build time if not supported?

File: src/skin/qml/qmlskin.cpp [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+    Q_UNUSED(pSkinCreatedControls);
+    VERIFY_OR_DEBUG_ASSERT(isValid()) {
+        return nullptr;
+    }
+
+    qmlRegisterType<QmlControlProxy>("Mixxx", 0, 1, "ControlProxy");
+
+    QmlPlayerManagerProxy* pPlayerManagerProxy = new QmlPlayerManagerProxy(
+            pCoreServices->getPlayerManager().get(), pParent);
+    qmlRegisterSingletonInstance("Mixxx", 0, 1, "PlayerManager", pPlayerManagerProxy);
```
Comment (Holzhaus) [inline src/skin/qml/qmlskin.cpp:115]: @uklotzde we just need to add a `QT_VERSION_CHECK` around these 3 lines, but then the singleton won't be available in the demo skin.

**Comment by Holzhaus** [comment]
The last commit should fix the issue, let's hope CI agrees.

**Comment by Holzhaus** [comment]
Can someone help me with the lambda? I have no idea why it doesn't work. It works on my machine and it's more or less copied from the Qt 5.12 documentation:

```
/home/runner/work/mixxx/mixxx/src/skin/qml/qmlskin.cpp: In member function ‘virtual QWidget* mixxx::skin::qml::QmlSkin::loadSkin(QWidget*, UserSettingsPointer, QSet<ControlObject*>*, mixxx::CoreServices*) const’: 

904Error: /home/runner/work/mixxx/mixxx/src/skin/qml/qmlskin.cpp:126:14: error: cannot convert ‘mixxx::skin::qml::QmlSkin::loadSkin(QWidget*, UserSettingsPointer, QSet<ControlObject*>*, mixxx::CoreServices*) const::<lambda(QQmlEngine*, QJSEngine*)>’ to ‘QObject* (*)(QQmlEngine*, QJSEngine*)’ 

905 126 | }); 

906 | ^ 

907 | | 

908 | mixxx::skin::qml::QmlSkin::loadSkin(QWidget*, UserSettingsPointer, QSet<ControlObject*>*, mixxx::CoreServices*) const::<lambda(QQmlEngine*, QJSEngine*)> 

909In file included from /usr/include/x86_64-linux-gnu/qt5/QtQml/qqmlengine.h:47, 

910 from /usr/include/x86_64-linux-gnu/qt5/QtQml/QQmlEngine:1, 

911 from /home/runner/work/mixxx/mixxx/src/skin/qml/qmlskin.cpp:3: 

912/usr/include/x86_64-linux-gnu/qt5/QtQml/qqml.h:635:44: note: initializing argument 5 of ‘int qmlRegisterSingletonType(const char*, int, int, const char*, QObject* (*)(QQmlEngine*, QJSEngine*)) [with T = mixxx::skin::qml::QmlPlayerManagerProxy]’ 

913 635 | QObject *(*callback)(QQmlEngine *, QJSEngine *)) 

914 | 

```

**Comment by Holzhaus** [comment]
I don't know what to do. Can someone with better C++ knowledge weigh in? `qmlRegisterSingletonType` expects a pointer to a function with the following signature:

    QObject* factoryFunction(QmlEngine*, QJSEngine*);

I tried:
- Passing in a capturing lambda
- Passing in a capturing lambda with return type annotation
- Passing in a `std::function` created from a capturing lambda with return type annotation

All of this works for me with gcc 10.2.0. The latter also fixed the CI build on Ubuntu 20.04, but still fails on macOS (AppleClang 12.0.0.12000032) and causes a "no known conversion" error. Any ideas how to fix it?

File: src/skin/qml/qmlplayerproxy.cpp [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+    emit albumChanged();
+    emit albumArtistChanged();
+    emit genreChanged();
+    emit composerChanged();
+    emit groupingChanged();
+    emit yearChanged();
+    emit trackNumberChanged();
+    emit trackTotalChanged();
+    emit commentChanged();
+    emit keyChanged();
```
Comment (uklotzde) [inline src/skin/qml/qmlplayerproxy.cpp:89]: I suggest to use the property name `keyText` consistently.

File: src/skin/qml/qmlplayerproxy.cpp [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+    }
+    emit trackChanged();
+    emit trackLoaded();
+}
+
+void QmlPlayerProxy::slotLoadingTrack(TrackPointer pNewTrack, TrackPointer pOldTrack) {
+    Q_UNUSED(pNewTrack);
+    Q_UNUSED(pOldTrack);
+    const TrackPointer pTrack = m_pCurrentTrack;
+    if (pTrack != nullptr) {
```
Comment (uklotzde) [inline src/skin/qml/qmlplayerproxy.cpp:69]: You can omit the noisy `!=/== nullptr` comparisons, unless you explicitly need to return a boolean value.

Comment (Holzhaus) [reply src/skin/qml/qmlplayerproxy.cpp:73]: Didn't leaving it out cause conversion warnings? Also, it's more explicit IMHO.

File: src/skin/qml/qmlplayerproxy.cpp [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+            return TYPE();                           \
+        }                                            \
+        return pTrack->GETTER();                     \
+    }                                                \
+                                                     \
+    void QmlPlayerProxy::SETTER(const TYPE& value) { \
+        const TrackPointer pTrack = m_pCurrentTrack; \
+        if (pTrack != nullptr) {                     \
+            pTrack->SETTER(value);                   \
+            emit NAME##Changed();                    \
```
Comment (daschuer) [inline src/skin/qml/qmlplayerproxy.cpp:24]: Why signal here, rather than subscribe the track signal?

Comment (Holzhaus) [reply src/skin/qml/qmlplayerproxy.cpp:24]: the track doesn't expose signals for each property.

Comment (daschuer) [reply src/skin/qml/qmlplayerproxy.cpp:24]: Yes. You set the track property, the track checks if it has changed and emits the changed() signal.
this is cached in slotTrackChanged() and will emit the individual signal per property. 
So this one here should be redundant.

Comment (Holzhaus) [reply src/skin/qml/qmlplayerproxy.cpp:24]: I'd rather do the opposite and only emit the changed signal for poperties that actually changed. I'll look into adapting the track object.

File: src/skin/qml/qmlplayerproxy.cpp (hunk 3 above)
Comment (daschuer) [reply src/skin/qml/qmlplayerproxy.cpp:73]: This topic has a history. 
* original we don't care 
* @rryan has started to make it explicit
* @uklotzde has removed the explicit comparisons

I still don't care, but prefer the implicit bool conversion for my code, because it is part of the std pointer api: 
https://en.cppreference.com/w/cpp/memory/shared_ptr/operator_bool

I would prefer to go back to the "Don't care" state for more developer freedom .. ;-)

Comment (uklotzde) [reply src/skin/qml/qmlplayerproxy.cpp:73]: The implicit version worked for both Qt and std managed pointers. That was the main reason for the preference. The explicit comparison with nullptr does not work for QSharedPointer and QScopedPointer afair.

File: src/skin/qml/qmlplayerproxy.cpp (hunk 4 above)
Comment (Holzhaus) [reply src/skin/qml/qmlplayerproxy.cpp:24]: Should I rebase on #3924 or do we want to go with a more iterative approach?

File: src/skin/qml/qmlplayerproxy.cpp (hunk 3 above)
Comment (Holzhaus) [reply src/skin/qml/qmlplayerproxy.cpp:73]: Is there any reason to use the Qt versions? I thought they were obsolete with C++ smart pointers.

Comment (uklotzde) [reply src/skin/qml/qmlplayerproxy.cpp:73]: No mass refactorings, that's the reason why.

**Comment by uklotzde** [comment]
If rebasing on #3924 avoids introducing temporary glue code then let's do it.

File: src/skin/qml/qmlplayerproxy.cpp (hunk 3 above)
Comment (daschuer) [reply src/skin/qml/qmlplayerproxy.cpp:73]: The only reason for QShared and QWeak pointers is that they integrates with the Qt object tree that is available anyway When using QObjects.

Comment (uklotzde) [reply src/skin/qml/qmlplayerproxy.cpp:73]: Apart from a built-in qobjectCast there is no documentation of any special behavior for QObject? Don't confuse it with QPointer which is different.

**Review by uklotzde — APPROVED** [review]
Routing each individual signal through the proxy is error prone and smells like an anti-pattern to me. But I am not aware of a better solution yet.

These fine-grained, two-way data bindings get out of control and become unmaintainable soon, because you lose the notion of discrete states and their transitions. But that's a different topic that we cannot solve here ;)

**Review by uklotzde — APPROVED** [review]
Since this might not be the final version let's use it for the moment to get more experience how to handle dependent properties in QML properly.

Thank you all this prototyping work! I am well aware that this is often the most challenging phase of a project :stuck_out_tongue: LGTM
