### PR TITLE
SoundSourceFLAC: Fix armv7hl build on gcc 11.1

### PR DESCRIPTION
**Pull request by uklotzde**
https://koji.rpmfusion.org/kojifiles/work/tasks/9174/489174/build.log

```
../src/sources/soundsourceflac.cpp: In member function 'FLAC__StreamDecoderWriteStatus mixxx::SoundSourceFLAC::flacWrite(const FLAC__Frame*, const FLAC__int32* const*)':
../src/sources/soundsourceflac.cpp:426:41: error: comparison of integer expressions of different signedness: 'mixxx::audio::SampleRate::value_t' {aka 'unsigned int'} and 'SINT' {aka 'int'} [-Werror=sign-compare]
  426 |     if (getSignalInfo().getSampleRate() != SINT(frame->header.sample_rate)) {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

### CODE REVIEW

**Comment by uklotzde** [comment]
Ping. I need this to kick off another build without including custom patches.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.
