### PR TITLE
(fix) Waveforms: don't scratch on mousepress/move with empty waveform

### LINKED ISSUE #15088: WaveformViewer allows mouse scratching even with no waveform loaded
Disable waveforms (or select 'Empty' in older versions) and you can still scratch the loaded track.

IMO we should turn this off when there's no waveform for visual feedback.
It's kinda dangerous / unexpected that interacting with an empty area affects the playback :|

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #15088

### CODE REVIEW

File: src/widget/wwaveformviewer.cpp [hunk 1]
```diff
@@ -77,7 +77,7 @@ void WWaveformViewer::showEvent(QShowEvent* event) {
 }
 
 void WWaveformViewer::mousePressEvent(QMouseEvent* event) {
-    if (!m_waveformWidget) {
+    if (!m_waveformWidget || m_waveformWidget->getType() == WaveformWidgetType::EmptyWaveform) {
```
Comment (ronso0) [inline src/widget/wwaveformviewer.cpp:80]: What's the problem here?
It's used exactly like here in line 306.
https://github.com/mixxxdj/mixxx/blob/e3eea8b239a81880796d8ba9a7fe477235834368/src/widget/wwaveformviewer.cpp#L306

**Review by m0dB — APPROVED** [review]
LGTM, I don't understand the compilation errors, compiles fine locally.

**Comment by JoergAtGithub** [comment]
I think the compilation errors are cached data from the time before retargeting this PR to the 2.5 branch. I don't see them, if I scroll over the build logs.

**Review by Swiftb0y — APPROVED** [review]
Yeah, they don't make any sense to me either. Lets just merge and see what happens.

**Comment by ronso0** [comment]
Umm, I can't scratch with the waveforms anymore in 2.6
:thinking:

**Comment by ronso0** [comment]
Uff, it happens after running into #14801 and reverting to RGB accelerated.
Waveform is there -- no scratching though

@acolombier @m0dB do you have time to take a look?

**Comment by JoergAtGithub** [comment]
@ronso0 Is 2.5 also affected?

**Comment by ronso0** [comment]
No, seems to be related to waveform options rework in 2.6
I've filed #15272 

But reverting this "fixes" it.
