### PR TITLE
Library: Sort by column with the cursor on it

### PR DESCRIPTION
**Pull request by JoergAtGithub**
This PR adds the possibility to sort the library from controler, which can move the cursor in the library table horizontal (relative position).

The command in the controler mapping will be:
engine.setValue("[Library]", "sort_column_toggle", -1);

This value was added to the enum already listed with the absolute references in https://github.com/mixxxdj/mixxx/wiki/mixxxcontrols

This PR replaces #3103

### CODE REVIEW

File: src/library/trackmodel.h [hunk 1]
```diff
@@ -49,6 +49,7 @@ class TrackModel {
     Q_DECLARE_FLAGS(Capabilities, Capability)
 
     enum SortColumnId {
+        SORTCOLUMN_CURRENTINDEX = -2, // Column with the cursor on it
```
Comment (Holzhaus) [inline src/library/trackmodel.h:52]: Can you swap these two, so that current is -1?i think we can safely do that.

**Comment by ronso0** [comment]
What's the reason for not addign this to 2.3?

File: src/library/trackmodel.h (hunk 1 above)
Comment (JoergAtGithub) [reply src/library/trackmodel.h]: I swapped the numerical values!

**Comment by JoergAtGithub** [comment]
> What's the reason for not addign this to 2.3?
I thought new features are no longer allowed in 2.3 - should I rebase to 2.3?

**Comment by ronso0** [comment]
This is basically true, but I considered this as some sort of finalization for the 'sort from controller' feature.
Let's wait what other's say. @Holzhaus @daschuer ?

**Comment by Holzhaus** [comment]
I'd be in favor of merging this into with 2.3.

**Comment by Holzhaus** [comment]
Please rebase on 2.3 and change the target branch.

**Comment by ronso0** [comment]
alright, then we also need proper focus highlight for table cells for 2.3

**Comment by JoergAtGithub** [comment]
I rebase this to 2.3, but now the GitHub Diff says every single line of th modified files is changed. What did I wrong?

**Comment by Holzhaus** [comment]
Windows vs Unix line endings?

**Comment by JoergAtGithub** [comment]
That makes sense. I used the command statements from https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch instead of my usually client. Seems this behaves different here.

**Comment by Holzhaus** [comment]
You can check with `git diff -R` or `git show -R`. It swaps the two inputs. If it displays something like `^M` that is a carriage return from windows line endings.

**Comment by JoergAtGithub** [comment]
After a long fight with GIT, the PR is now rebased to 2.3. I tested the 2.3 build with my controller and all column sorting works fine, with mouse and with controller.

**Comment by uklotzde** [comment]
Can we please stash all those intermediate trial-and-error commits from rebasing before merging? They are not needed for the history of this fairly small change set.

File: src/widget/wtracktableview.cpp [hunk 2]
```diff
@@ -363,6 +363,11 @@ void WTrackTableView::slotMouseDoubleClicked(const QModelIndex& index) {
     }
 }
 
+int WTrackTableView::getColumnIdFromCurrentIndex() {
+    TrackModel* trackModel = getTrackModel();
```
Comment (uklotzde) [inline src/widget/wtracktableview.cpp:367]: Just in case:
```
VERIFY_OR_DEBUG_ASSERT(trackModel) {
        return;
}
```

File: src/library/trackmodel.h [hunk 3]
```diff
@@ -50,7 +50,8 @@ class TrackModel {
     typedef int CapabilitiesFlags; /** Enables us to do ORing */
 
     enum SortColumnId {
-        SORTCOLUMN_INVALID = -1,
+        SORTCOLUMN_INVALID = -2,
```
Comment (uklotzde) [inline src/library/trackmodel.h:53]: I am not particularly happy with this renumbering. Hopefully, -1 is not used literally anywhere in the existing code base like it is for invalid database ids. Using -1 for invalid ids is an omnipresent pattern in the code.

How can we be sure without turning `SortColumnId` into a type-safe `enum class`?

Comment (JoergAtGithub) [reply src/library/trackmodel.h:53]: I changed this on behalf of @Holzhaus , who introduced this enum in https://github.com/mixxxdj/mixxx/commit/5325677de850a5da25155e56d3e1a7ac10a1c0b3#diff-0d9324681e3f544722e2b0d3ee2834a83c25ce51988247b12865bb94ce2bc4f3
I guess he rated this enumeration change as safe, because it's new in 2.3 and therefore nobody could use it in his mappings.

Comment (Holzhaus) [reply src/library/trackmodel.h:53]: The alternative would be to use 0 for the current column and change all other enum values. Then you'd also need to check if any mappings in 2.3 or master already use this CO (at least the Roland DJ-505 does).

File: src/widget/wtracktableview.cpp (hunk 2 above)
Comment (JoergAtGithub) [reply src/widget/wtracktableview.cpp:367]: Done!

File: src/library/trackmodel.h (hunk 3 above)
Comment (uklotzde) [reply src/library/trackmodel.h:53]: ...or use -2 as initially proposed? -1 is a very special value in the Mixxx code base and also in Qt for *invalid* values.

Comment (JoergAtGithub) [reply src/library/trackmodel.h:53]: To change all other enum values, use 0 for current column and -1 for invalid seems to be the cleanest state.
It would affect the Roland DJ-505 mapping and the Denon MC7000 mapping, which are part of the 2.3 branch. Therefore I could adjust them in this PR.
The risk regarding backward compatibility would be, that other users of 2.3 or master development builds used this new CO in their mappings too, but no user of a released Mixxx versions would be affected by this change.

Comment (uklotzde) [reply src/library/trackmodel.h:53]: @Holzhaus Your opinion? I would support this decision for the sake of consistency, even though the actual values should not matter at all.

Comment (uklotzde) [reply src/library/trackmodel.h:53]: Well, of course, the values matter once they have been defined!

We should add a note that these enum values are used literally by controller scripts and must never be changed! Unfortunately, the values of this enum are defined implicitly and not visible in the code.

Comment (uklotzde) [reply src/library/trackmodel.h:53]: Both reordering or insertion of new enum variants is strictly forbidden! New variants must always be inserted between the last valid and before the terminating variant.

Comment (JoergAtGithub) [reply src/library/trackmodel.h:53]: < Unfortunately, the values of this enum are defined implicitly and not visible in the code.

Should I define all the values of this enum explicit, except NUM_SORTCOLUMNIDS of cause?

Comment (uklotzde) [reply src/library/trackmodel.h:53]: That might help to communicate the intention and restrictions of this enum. We should also define SORTCOLUMN_ID_MIN/MAX, with NUM_SORTCOLUMNIDS = SORTCOLUMN_ID_COUNT = (SORTCOLUMN_ID_MAX - SORTCOLUMN_ID_MIN) + 1. Currently, the code implicitly assumes that 0 is the first and NUM_SORTCOLUMNIDS - 1 the last valid value, i.e. strictly 0-based.

Comment (Holzhaus) [reply src/library/trackmodel.h:53]: > Well, of course, the values matter once they have been defined!
> 
> We should add a note that these enum values are used literally by controller scripts and must never be changed! Unfortunately, the values of this enum are defined implicitly and not visible in the code.

Yes. In this special case it has never been part of a stable Mixxx release so I assume it's okay. I'd support redefining the column id such that 0 means the current column. It only affects two controller mappings:

```
$ git grep -l sort_column
res/controllers/Denon-MC7000-scripts.js
res/controllers/Roland_DJ-505-scripts.js
src/library/librarycontrol.cpp
src/widget/wtracktableview.cpp
```

Comment (Holzhaus) [reply src/library/trackmodel.h:53]: @JoergAtGithub When a decision is made here, can you please file a PR for the manual repo to update the CO documention: https://manual.mixxx.org/2.3/en/chapters/advanced_topics.html#control-[Library]-sort_column

Comment (JoergAtGithub) [reply src/library/trackmodel.h:53]: I searched through the code for NUM_SORTCOLUMNIDS, and found that the enum is not only used for the sorting feature, but also for import and export of different library formats. I found several arrays and loops like this:
`int m_columnIndexBySortColumnId[NUM_SORTCOLUMNIDS];`

`for (int i = 0; i < TrackModel::SortColumnId::NUM_SORTCOLUMNIDS; ++i) {`
`        m_columnIndexBySortColumnId[i] = -1;`
`}`
This all relies on the first ID of a real column to be zero.

To change this would make this code complicated and difficult to read. Therefore I sugest not to shift the definition of this enumeration.

Comment (Holzhaus) [reply src/library/trackmodel.h:53]: These loops are for looking up the actual column id for a given sort column ID. I think you need `m_columnIndexBySortColumnId[0] = -1` to indicate that SortColumnId 0 does not map to a special column.

Comment (JoergAtGithub) [reply src/library/trackmodel.h]: I changed the values of the SORTCOLUMIDs now as suggested.
I tested sort_column_toggle with all values from -1 to 30:
- I couldn't find a table view, where SORTCOLUMN_SAMPLERATE (value 29) is used
- Sorting with SORTCOLUMN_LOCATION (value 25) seems to be not implement - it does not work for this column. But I think, this is independent from this PR

File: src/library/browse/browsetablemodel.cpp [hunk 4]
```diff
@@ -133,8 +135,8 @@ BrowseTableModel::~BrowseTableModel() {
 }
 
 int BrowseTableModel::columnIndexFromSortColumnId(TrackModel::SortColumnId column) {
-    if (column < TrackModel::SortColumnId::SORTCOLUMN_ID_MIN|
-        column > TrackModel::SortColumnId::SORTCOLUMN_ID_MAX) {
+    if (column<TrackModel::SortColumnId::SORTCOLUMN_ID_MIN ||
+                column>TrackModel::SortColumnId::SORTCOLUMN_ID_MAX) {
```
Comment (Holzhaus) [inline src/library/browse/browsetablemodel.cpp:139]: Are you using out pre-commit hooks? I thought it enforces spaces around operators. In any case, please fix.

File: src/library/trackmodel.h [hunk 5]
```diff
@@ -62,7 +62,7 @@ class TrackModel {
         SORTCOLUMN_YEAR = 5,
         SORTCOLUMN_GENRE = 6,
         SORTCOLUMN_COMPOSER = 7,
-m        SORTCOLUMN_GROUPING = 8,
```
Comment (Holzhaus) [inline src/library/trackmodel.h]: This looks like a potential compilation error. All commits should be compilable without errors. If you accidently commited a broken state, please fixup the erroneous commits and force-push.

File: src/library/browse/browsetablemodel.cpp (hunk 4 above)
Comment (JoergAtGithub) [reply src/library/browse/browsetablemodel.cpp]: No, I'm on Windows, where this is not available.
I used git apply with the patch file from CI.

File: src/library/trackmodel.h (hunk 5 above)
Comment (JoergAtGithub) [reply src/library/trackmodel.h]: Already fixed!

Comment (Holzhaus) [reply src/library/trackmodel.h]: Yes, but if I'm doing a git bisect and try to build commit https://github.com/mixxxdj/mixxx/pull/3167/commits/5fdcb305ae3de40083c343b8835abbb3029f9a03 it will fail. Please run:

git rebase -i HEAD~2 and replace `pick` in front of `a20bddd` with `fixup`.

Comment (JoergAtGithub) [reply src/library/trackmodel.h]: Done!

File: src/library/browse/browsetablemodel.cpp (hunk 4 above)
Comment (Holzhaus) [reply src/library/browse/browsetablemodel.cpp]: I think it is available now, but you need to install `clang-format` separately.

File: src/widget/wtracktableview.cpp [hunk 6]
```diff
@@ -937,7 +945,8 @@ void WTrackTableView::applySortingIfVisible() {
 void WTrackTableView::applySorting() {
     TrackModel* trackModel = getTrackModel();
     int sortColumnId = static_cast<int>(m_pSortColumn->get());
-    if (sortColumnId < 0 || sortColumnId >= TrackModel::SortColumnId::NUM_SORTCOLUMNIDS) {
+    if (sortColumnId < TrackModel::SortColumnId::SORTCOLUMN_ID_MIN ||
+            sortColumnId > TrackModel::SortColumnId::SORTCOLUMN_ID_MAX) {
```
Comment (Holzhaus) [inline src/widget/wtracktableview.cpp:949]: Shoud this be a VERIFY_OR_DEBUG_ASSERT?

**Review by Holzhaus — APPROVED** [review]
Works good.

**Comment by Holzhaus** [comment]
Can you rebase on latest upstream/2.3 (or merge it)? I suspect the CI build failures should be solved then.

File: src/library/trackmodel.h [hunk 7]
```diff
@@ -49,41 +49,48 @@ class TrackModel {
     };
     typedef int CapabilitiesFlags; /** Enables us to do ORing */
 
+    // Note that these enum values are used literally by controller scripts and must never be changed!
+    // Both reordering or insertion of new enum variants is strictly forbidden!
+    // New variants must always be inserted between the last valid and before the terminating variant SORTCOLUMN_ID_MAX!
     enum SortColumnId {
```
Comment (Holzhaus) [inline src/library/trackmodel.h:55]: Can you make this an enum class and use camelCase for the enum members?

Comment (JoergAtGithub) [reply src/library/trackmodel.h:55]: I tried to use **enum class SortColumnId : int {** instead of **enum SortColumnId {** but that requires a **static_cast<< int >>** for every single place where it's used. Is that what you intend?

Comment (Holzhaus) [reply src/library/trackmodel.h:55]: Yes.

Comment (JoergAtGithub) [reply src/library/trackmodel.h:55]: But isn't type saveness the reason for an enum class? If I use it everywhere wit static_cast, there is no type saveness at all...

Comment (Holzhaus) [reply src/library/trackmodel.h:55]: Scoping is also another reason for it.

Comment (JoergAtGithub) [reply src/library/trackmodel.h]: Done!

File: src/library/basesqltablemodel.cpp [hunk 8]
```diff
@@ -70,38 +70,90 @@ void BaseSqlTableModel::initHeaderProperties() {
...
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_TIMESPLAYED] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_TIMESPLAYED);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_RATING] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_RATING);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_KEY] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_KEY);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_PREVIEW] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_PREVIEW);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_COLOR] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_COLOR);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_COVERART] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_COVERART);
-    m_columnIndexBySortColumnId[TrackModel::SortColumnId::SORTCOLUMN_SAMPLERATE] = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_SAMPLERATE);
+    m_columnIndexBySortColumnId[static_cast<int>(
+            TrackModel::SortColumnId::sortColumnArtist)] =
```
Comment (Holzhaus) [inline src/library/basesqltablemodel.cpp:77]:
```suggestion
            TrackModel::SortColumnId::Artist)] =
```

The `sortColumn` prefix is redundant now

**Review by Holzhaus — CHANGES_REQUESTED** [review]

File: src/library/basesqltablemodel.cpp (hunk 8 above)
Comment (JoergAtGithub) [reply src/library/basesqltablemodel.cpp]: Done!

**Comment by JoergAtGithub** [comment]
@Holzhaus : Is this Ok in your view now?

**Comment by Holzhaus** [comment]
> @Holzhaus : Is this Ok in your view now?

I think so, give me some time until I had the chance to test this with my controller.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. Please resolve the merge conflicts for mixxxdj/manual#232 so that we can merge this.
