### PR TITLE
Opus encoder

### PR DESCRIPTION
**Pull request by Palakis**
Features:
- Works for Recording and/or Live Broadcasting
- Track Metadata for Recording (LB metadata is handled differently)
- CBR and VBR modes

Started as an internal PR on my fork. Original conversation here: https://github.com/Palakis/mixxx/pull/3

### CODE REVIEW

**Comment by Palakis** [comment]
Among other small bugs, here's an interesting comment by @daschuer from the [original pull request](https://github.com/Palakis/mixxx/pull/3):

> The encoding type options are getting overwhelmed. Could you add a tooltip for each option, with a > hint for what it should be used:
> 
> "Mp3, old but plays everywhere"
> "Ogg Vobis, the free an better codec"
> "Opus, the Vobis successor"
> "AAC ...
>
> We can optimize these strings now or later

**Comment by daschuer** [comment]
Thank you for this PR. Is it a candidate for 2.1?
Is it ready for reviewing?

**Comment by Palakis** [comment]
@daschuer It is a candidate for 2.1, ready for reviewing.

File: src/encoder/encoderopus.cpp [hunk 1]
```diff
@@ -0,0 +1,439 @@
...
+            m_channels = 2;
+            break;
+        case EncoderSettings::ChannelMode::AUTOMATIC:
+            m_channels = 2;
+            break;
+    }
+}
+
+int EncoderOpus::initEncoder(int samplerate, QString errorMessage) {
+    (void)errorMessage;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Looks weird. Please use Q_UNUSED() or simply omit the parameter name.

File: src/encoder/encoderopus.cpp [hunk 2]
```diff
@@ -0,0 +1,439 @@
...
+    int result;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: unused

File: src/encoder/encoderopus.cpp [hunk 3]
```diff
@@ -0,0 +1,439 @@
...
+
+    if (samplerate != 48000) {
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: no magic numbers inside the code, please use constexpr in anonymous namespace

File: src/encoder/encoderopus.cpp [hunk 4]
```diff
@@ -0,0 +1,439 @@
...
+        kLogger.warning() << "initEncoder failed: samplerate not supported by Opus";
+
+        QString invalidSamplerate = QObject::tr(
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Almost the same message is used in ShoutConnection, even using the same "magic numbers". Please try to minimize redundant code and decide according to the dependencies were to place shared code and constants.

File: src/encoder/encoderopus.cpp [hunk 5]
```diff
@@ -0,0 +1,439 @@
...
+    if (result != OPUS_OK) {
+        kLogger.warning() << "opus_encoder_create failed:" << opusErrorString(result);
+        return -1;
+    }
+
+    // Optimize encoding for high-quality music
+    opus_encoder_ctl(m_pOpus, OPUS_SET_COMPLEXITY(10)); // Highest setting
+    opus_encoder_ctl(m_pOpus, OPUS_SET_SIGNAL(OPUS_SIGNAL_MUSIC));
+
+    if(m_bitrateMode == 0) {
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: This should be an enum or at least the constants should explicitly be defined somewhere. As readable code and not only hidden inside comments. Code is validated by the compiler, comments are not.

File: src/encoder/encoderopus.cpp [hunk 6]
```diff
@@ -0,0 +1,439 @@
...
+    // - Version: 1 byte
+    // - Channel count: 1 byte
+    // - Pre-skip: 2 bytes
+    // - Samplerate: 4 bytes
+    // - Output Gain: 2 bytes
+    // - Mapping family: 1 byte
+    // - Channel mapping table: ignored
+    // Total: 19 bytes
+    const int frameSize = 19;
+    unsigned char* data = new unsigned char[frameSize]();
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Plain pointers are evil and the extra () is unnecessary. Why don't you use an array that is statically allocated on the stack? It's just 19 bytes.

File: src/encoder/encoderopus.cpp [hunk 7]
```diff
@@ -0,0 +1,439 @@
...
+	  m_readRequired(0),
+      m_pCallback(pCallback),
+      m_pFifoBuffer(nullptr),
+      m_pFifoChunkBuffer(nullptr),
+      m_pOpus(nullptr),
+      m_header_write(false),
+      m_packetNumber(0),
+      m_granulePos(0) {
+    m_opusComments.insert("ENCODER", "mixxx/libopus");
+    m_pOpusDataBuffer = new unsigned char[kMaxOpusBufferSize]();
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: The size is known at compile time, so this array does not need to be allcated dynamically on the heap. And even if you decide to do so I would recommend using either std::vector or QVector.

File: src/encoder/encoderopus.cpp [hunk 8]
```diff
@@ -0,0 +1,439 @@
...
+        }
+        combinedComments.append(commentBytes);
+
+        // Don't forget to include this comment in the overall size calculation
+        frameSize += (4 + commentBytesLength);
+        commentCount++;
+    }
+
+    // == Actual frame building ==
+    unsigned char* data = new unsigned char[frameSize]();
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Please avoid old skool manual memory management and instead use std::vector or QVector.

File: src/encoder/encoderopus.cpp [hunk 9]
```diff
@@ -0,0 +1,439 @@
...
+    int pos = 0; // Current position
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: double bookkeeping is unnecessary if you advance the data pointer directly

File: src/encoder/encoderopus.cpp [hunk 10]
```diff
@@ -0,0 +1,439 @@
...
+    // This is set to the buffer size of the sidechain engine because
+    // Recording (which uses this engine) sends more samples at once to the encoder than
+    // the Live Broadcasting implementation
+    m_pFifoBuffer = new FIFO<CSAMPLE>(EngineSideChain::SIDECHAIN_BUFFER_SIZE * 2);
+
+    double samplingPeriodMs = (1.0/((float)m_samplerate)) * 1000.0;
+    double samplesPerChannel = kOpusFrameMs / samplingPeriodMs;
+
+    m_readRequired = samplesPerChannel * m_channels;
+    m_pFifoChunkBuffer = new CSAMPLE[m_readRequired * sizeof(CSAMPLE)]();
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Please use SampleBuffer instead of doing your own memory management. This would have prevented the error to over-allocate memory by multiplying with sizeof(CSAMPLE)

File: src/encoder/encoderopus.cpp [hunk 11]
```diff
@@ -0,0 +1,439 @@
...
+
+    // Size the input FIFO buffer with twice the maximum possible sample count that can be
+    // processed at once, to avoid skipping frames or waiting for the required sample count
+    // and encode at a regular pace.
+    // This is set to the buffer size of the sidechain engine because
+    // Recording (which uses this engine) sends more samples at once to the encoder than
+    // the Live Broadcasting implementation
+    m_pFifoBuffer = new FIFO<CSAMPLE>(EngineSideChain::SIDECHAIN_BUFFER_SIZE * 2);
+
+    double samplingPeriodMs = (1.0/((float)m_samplerate)) * 1000.0;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Why do you cast to float if you actually want a double? Please use spaces before/after operators to improve readability.

File: src/encoder/encoderopus.cpp [hunk 12]
```diff
@@ -0,0 +1,439 @@
...
+        opus_encoder_ctl(m_pOpus, OPUS_SET_VBR_CONSTRAINT(0)); // Unconstrained VBR
+    }
+
+    // Size the input FIFO buffer with twice the maximum possible sample count that can be
+    // processed at once, to avoid skipping frames or waiting for the required sample count
+    // and encode at a regular pace.
+    // This is set to the buffer size of the sidechain engine because
+    // Recording (which uses this engine) sends more samples at once to the encoder than
+    // the Live Broadcasting implementation
+    m_pFifoBuffer = new FIFO<CSAMPLE>(EngineSideChain::SIDECHAIN_BUFFER_SIZE * 2);
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: The FIFO buffer does not need to be allocated dynamically. The footprint of FIFO itself is small. The actual buffer is allocated dynamically behind the scenes.

File: src/encoder/encoderopus.cpp [hunk 13]
```diff
@@ -0,0 +1,439 @@
...
+      m_header_write(false),
+      m_packetNumber(0),
+      m_granulePos(0) {
+    m_opusComments.insert("ENCODER", "mixxx/libopus");
+    m_pOpusDataBuffer = new unsigned char[kMaxOpusBufferSize]();
+    ogg_stream_init(&m_oggStream, rand());
+}
+
+EncoderOpus::~EncoderOpus() {
+    if (m_pOpus)
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Please use curly braces even if the scope is only a single line.

File: src/encoder/encoderopus.cpp [hunk 14]
```diff
@@ -0,0 +1,439 @@
...
+        opus_encoder_destroy(m_pOpus);
+
+    ogg_stream_clear(&m_oggStream);
+    delete[] m_pOpusDataBuffer;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Those deletes should vanish finally

File: src/encoder/encoderopus.cpp [hunk 15]
```diff
@@ -0,0 +1,439 @@
...
+    while (!eos) {
+        int result = ogg_stream_pageout(&m_oggStream, &m_oggPage);
+        if (result == 0) {
+            break;
+        }
+
+        m_pCallback->write(m_oggPage.header, m_oggPage.body,
+                           m_oggPage.header_len, m_oggPage.body_len);
+
+        if (ogg_page_eos(&m_oggPage)) {
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: do { ... } while (ogg_page_eos());

File: src/encoder/encoderopus.cpp [hunk 16]
```diff
@@ -0,0 +1,439 @@
...
+    packet.b_o_s = 0;
+    packet.e_o_s = 0;
+    packet.granulepos = 0;
+    packet.packetno = m_packetNumber++;
+    packet.packet = data;
+    packet.bytes = frameSize;
+
+    kLogger.debug() << data;
+
+    ogg_stream_packetin(&m_oggStream, &packet);
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: I would recommend to validate all return values of an external library

File: src/encoder/encoderopus.cpp [hunk 17]
```diff
@@ -0,0 +1,439 @@
...
+    }
+
+    processFIFO();
+}
+
+void EncoderOpus::processFIFO() {
+    while (m_pFifoBuffer->readAvailable() >= m_readRequired) {
+        m_pFifoBuffer->read(m_pFifoChunkBuffer, m_readRequired);
+
+        int samplesPerChannel = m_readRequired / m_channels;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Here you might drop some samples. I would at least check with a debug assertion that indeed (m_readRequired % m_channels) == 0 as expect. This will safe you a lot of debugging time if your assumption is wrong, maybe because of some programming error somewhere else.

File: src/encoder/encoderopus.cpp [hunk 18]
```diff
@@ -0,0 +1,439 @@
...
+        int result = opus_encode_float(m_pOpus, m_pFifoChunkBuffer, samplesPerChannel,
+                m_pOpusDataBuffer, kMaxOpusBufferSize);
+
+        if (result < 1) {
+            kLogger.warning() << "opus_encode_float failed:" << opusErrorString(result);
+            return;
+        }
+
+        ogg_packet packet;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Wouldn't it be possible to reduce the number of member variable by introducing ogg_packet m_nextPacket?

Comment (uklotzde) [reply src/encoder/encoderopus.cpp]: Maybe not, because the signature of ogg_stream_packetin() allows to modify the contents of the packet.

**Comment by JosepMaJAZ** [comment]
We currently build against opusfile 0.7 and opus 1.1.2, which does not contain some of the functions required. We need to update (windows) buildserver libs.

**Comment by Palakis** [comment]
Hmm, SampleBuffer causes no trouble on my machine, but seems like Travis can't find it...

**Comment by Sa-Ja-Di** [comment]
So there is a chance that in the next version streaming in Opus is a possibility? I would love that very much as even 48 kbps in Opus is a damn fine quality. Hope you can make it :)

**Comment by daschuer** [comment]
Travis build the merge with master. I can reproduce the build failure on my stem after merging master. So I assume it is a kind of merge conflict.

**Comment by daschuer** [comment]
@Palakis: will you have time to finish this for Mixxx 2.2?

**Comment by Palakis** [comment]
@daschuer Sure! I'll have a look at the build failure next week and see what's left to fix.

**Comment by Palakis** [comment]
I fixed the merge conflict. Linux CI passes without issues, however Windows and macOS fail with "undefined symbol" errors, each platform showing a different set of missing symbols.

Windows:
```
   Creating library win64_build\mixxx.lib and object win64_build\mixxx.exp
opusfile.lib(enc_API.obj) : error LNK2019: unresolved external symbol silk_encode_do_VAD_FLP referenced in function silk_Encode
opusfile.lib(enc_API.obj) : error LNK2019: unresolved external symbol silk_encode_frame_FLP referenced in function silk_Encode
win64_build\mixxx.exe : fatal error LNK1120: 2 unresolved externals
```

macOS:
```
Undefined symbols for architecture x86_64:
  "_opus_encode_float", referenced from:
      EncoderOpus::processFIFO() in encoderopus.o
```

**Comment by Palakis** [comment]
macOS builds fixed!

**Comment by Be-ing** [comment]
Is this still a candidate for 2.2 or should we push it back to 2.3? It looks like there is a lot of new code to review here and I am doubting it should be rushed for 2.2 in the next week.

**Comment by Palakis** [comment]
@Be-ing 
> Is this still a candidate for 2.2 or should we push it back to 2.3? It looks like there is a lot of new code to review here and I am doubting it should be rushed for 2.2 in the next week.

It's ready for review, but push it back to 2.3. There still is a linking issue on Windows to fix.

**Comment by Palakis** [comment]
@daschuer @uklotzde This PR is ready for review. I fixed merged conflicts, code and compile issues. One issue remains with Windows CI, a PR has been issued to address it (https://github.com/mixxxdj/buildserver/pull/70).

macOS CI shouldn't have issues with opus, however I didn't manage to assert this as the macOS jobs get stuck during Homebrew, even on `master`.

**Comment by Palakis** [comment]
Update: https://github.com/mixxxdj/buildserver/pull/70 has been superseded by https://github.com/mixxxdj/buildserver/pull/71, which targets the 2.3 Windows buildserver.

File: src/encoder/encoder.cpp [hunk 19]
```diff
@@ -99,7 +109,14 @@ EncoderPointer EncoderFactory::getNewEncoder(Encoder::Format format,
         pEncoder = std::make_shared<EncoderVorbis>(pCallback);
         #endif
         pEncoder->setEncoderSettings(EncoderVorbisSettings(pConfig));
-    } else {
+    }
+    #ifdef __OPUS__
```
Comment (rryan) [inline src/encoder/encoder.cpp]: nit, no indent for preprocessor commands please

**Comment by rryan** [comment]
The buildserver build succeeded, so you can update build/windows/golden_environment to 
2.3-j00010-PLATFORM-CONFIGURATION-static-586a5384-minimal

**Comment by Palakis** [comment]
The buildserver build is missing some opus dependencies (`silk_float`, namely). Buildserver fix: https://github.com/mixxxdj/buildserver/pull/72

**Comment by Palakis** [comment]
Alright, build issues are fixed on AppVeyor for Windows and Linux. Gonna fix the remaining remarks.

File: src/encoder/encoderopus.cpp (hunk 17 above)
Comment (Palakis) [reply src/encoder/encoderopus.cpp]: Should be fixed: https://github.com/Palakis/mixxx/blob/opus-encoder/src/encoder/encoderopus.cpp#L344-L346

**Comment by Palakis** [comment]
Remaining remarks have been adressed! This is definitely ready for another review.

File: src/encoder/encoderopus.cpp [hunk 20]
```diff
@@ -0,0 +1,466 @@
...
+
+const mixxx::Logger kLogger("EncoderOpus");
+}
+
+EncoderOpus::EncoderOpus(EncoderCallback* pCallback)
+    : m_bitrate(0),
+      m_bitrateMode(0),
+      m_channels(0),
+      m_samplerate(0),
+	  m_readRequired(0),
```
Comment (daschuer) [inline src/encoder/encoderopus.cpp]: Stray tab?

**Comment by daschuer** [comment]
LGTM. Only a nit-pick.
Is there a receipt to test this one. A public test server or such?
Since this is an optional settings it is fine for me to merge it now and ask experienced forum user for a test.

Thoughts?

**Comment by daschuer** [comment]
By the way: thank you very much for this nice piece of code. It reads like a book. :-)

**Comment by Palakis** [comment]
@daschuer 
> LGTM. Only a nit-pick.

Fixed just now.

> Is there a receipt to test this one. A public test server or such?

I don't need anything at hand right now but I can setup something in that fashion. Do you want a 24/7 test stream or just a public Icecast test server?

> Since this is an optional settings it is fine for me to merge it now and ask experienced forum user for a test.

Fine for me too!

**Comment by Palakis** [comment]
@daschuer 

> By the way: thank you very much for this nice piece of code. It reads like a book. :-)

Aw, thanks! Really kind of you. :D

File: src/encoder/encoderopus.cpp [hunk 21]
```diff
@@ -0,0 +1,466 @@
...
+
+EncoderOpus::EncoderOpus(EncoderCallback* pCallback)
+    : m_bitrate(0),
+      m_bitrateMode(0),
+      m_channels(0),
+      m_samplerate(0),
+      m_readRequired(0),
+      m_pCallback(pCallback),
+      m_fifoBuffer(EngineSideChain::SIDECHAIN_BUFFER_SIZE * 2),
+      m_pFifoChunkBuffer(nullptr),
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Please use `std::unique_ptr` and remove the initialization

File: src/encoder/encoderopus.cpp [hunk 22]
```diff
@@ -0,0 +1,466 @@
...
+    ogg_stream_init(&m_oggStream, qrand());
+}
+
+EncoderOpus::~EncoderOpus() {
+    if (m_pOpus) {
+        opus_encoder_destroy(m_pOpus);
+    }
+
+    ogg_stream_clear(&m_oggStream);
+    delete m_pFifoChunkBuffer;
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: Obsolete with `std::unique_ptr`

File: src/encoder/encoderopus.cpp [hunk 23]
```diff
@@ -0,0 +1,466 @@
...
+        // == Full VBR ==
+        opus_encoder_ctl(m_pOpus, OPUS_SET_VBR(1));
+        opus_encoder_ctl(m_pOpus, OPUS_SET_VBR_CONSTRAINT(0)); // Unconstrained VBR
+    }
+
+    double samplingPeriodMs = ( 1.0 / ((double)m_samplerate) ) * 1000.0;
+    double samplesPerChannel = kOpusFrameMs / samplingPeriodMs;
+
+    m_readRequired = samplesPerChannel * m_channels;
+    m_pFifoChunkBuffer = new mixxx::SampleBuffer(m_readRequired);
```
Comment (uklotzde) [inline src/encoder/encoderopus.cpp]: use std::make_unique() (from "util/memory.h")

File: src/encoder/encoderopus.h [hunk 24]
```diff
@@ -0,0 +1,61 @@
...
+#include "util/fifo.h"
+#include "util/sample.h"
+#include "util/samplebuffer.h"
+
+class EncoderOpus: public Encoder {
+  public:
+    static const int MASTER_SAMPLERATE;
+    static const char* INVALID_SAMPLERATE_MESSAGE;
+
+    EncoderOpus(EncoderCallback* pCallback = nullptr);
```
Comment (uklotzde) [inline src/encoder/encoderopus.h]: `explicit`

File: src/encoder/encoderopus.h [hunk 25]
```diff
@@ -0,0 +1,61 @@
...
+    virtual ~EncoderOpus();
```
Comment (uklotzde) [inline src/encoder/encoderopus.h]: Replace `virtual` with `override`

File: src/encoder/encoderopus.h [hunk 26]
```diff
@@ -0,0 +1,61 @@
...
+
+    int initEncoder(int samplerate, QString errorMessage) override;
+    void encodeBuffer(const CSAMPLE *samples, const int size) override;
+    void updateMetaData(const QString& artist, const QString& title, const QString& album) override;
+    void flush() override;
+    void setEncoderSettings(const EncoderSettings& settings) override;
+
+  private:
+    static QString opusErrorString(int error);
```
Comment (uklotzde) [inline src/encoder/encoderopus.h]: Those two private static functions don't need access to OpusEncoder and can be hidden in the anonymous namespace

File: src/encoder/encoderopussettings.cpp [hunk 27]
```diff
@@ -0,0 +1,155 @@
...
+
+    // OptionsGroup needs a QList<string> for the option list. Using QMap::values()
+    // ensures that the returned QList<string> will be sorted in ascending key order, which
+    // is what we want to be able to match OPUS_BITRATE_* number defines to the right mode
+    // in EncoderOpus.
+    m_radioList.append(OptionsGroup(
+            QObject::tr("Bitrate Mode"), BITRATE_MODE_GROUP, modes.values()));
+}
+
+EncoderOpusSettings::~EncoderOpusSettings() {
```
Comment (uklotzde) [inline src/encoder/encoderopussettings.cpp]: Please remove the empty implementation and declare as `= default`

File: src/encoder/encoderopussettings.cpp [hunk 28]
```diff
@@ -0,0 +1,155 @@
...
+    }
+}
+
+QList<EncoderSettings::OptionsGroup> EncoderOpusSettings::getOptionGroups() const {
+    return m_radioList;
+}
+
+void EncoderOpusSettings::setGroupOption(QString groupCode, int optionIndex) {
+    bool found = false;
+    for (OptionsGroup group : m_radioList) {
```
Comment (uklotzde) [inline src/encoder/encoderopussettings.cpp]: qAsConst(m_radioList)

File: src/encoder/encoderopussettings.cpp [hunk 29]
```diff
@@ -0,0 +1,155 @@
...
+                << "Received an unknown groupCode on setGroupOption:" << groupCode;
+    }
+}
+
+int EncoderOpusSettings::getSelectedOption(QString groupCode) const {
+    int value = m_pConfig->getValue(
+            ConfigKey(RECORDING_PREF_KEY, BITRATE_MODE_GROUP), 0);
+
+    bool found = false;
+    for (OptionsGroup group : m_radioList) {
```
Comment (uklotzde) [inline src/encoder/encoderopussettings.cpp]: qAsConst(m_radioList)

File: src/encoder/encoderopussettings.h [hunk 30]
```diff
@@ -0,0 +1,60 @@
...
+
+#define OPUS_BITRATE_MODES_COUNT 3
+#define OPUS_BITRATE_CONSTRAINED_VBR 0
+#define OPUS_BITRATE_CBR 1
+#define OPUS_BITRATE_VBR 2
+
+class EncoderOpusSettings: public EncoderSettings {
+  public:
+    EncoderOpusSettings(UserSettingsPointer pConfig);
+    virtual ~EncoderOpusSettings();
```
Comment (uklotzde) [inline src/encoder/encoderopussettings.h]: `~EncoderOpusSettings() override = default;`

File: src/encoder/encoderopussettings.h [hunk 31]
```diff
@@ -0,0 +1,60 @@
...
+#include "encoder/encoder.h"
+
+#define OPUS_BITRATE_MODES_COUNT 3
+#define OPUS_BITRATE_CONSTRAINED_VBR 0
+#define OPUS_BITRATE_CBR 1
+#define OPUS_BITRATE_VBR 2
+
+class EncoderOpusSettings: public EncoderSettings {
+  public:
+    EncoderOpusSettings(UserSettingsPointer pConfig);
```
Comment (uklotzde) [inline src/encoder/encoderopussettings.h]: `explicit EncoderOpusSettings(...`

**Review by uklotzde — CHANGES_REQUESTED** [review]
I added some comments for some minor issues that should be fixed before merging.

There are even more minor code style issue (formatting, missing curly braces, const naming convention, C-style casts, ...) that you may leave as is if no one else complains ;)

**Comment by Palakis** [comment]
@uklotzde Thanks for your review! Fixed these issues.

**Review by uklotzde — APPROVED** [review]
Thanks @Palakis for getting this in shape quickly. This is a nice feature for 2.3, although I'm not able to test it myself. LGTM.

**Comment by uklotzde** [comment]
Merge?

**Comment by daschuer** [comment]
Yes. 
I think we should wait for Jenkins had all 2.3 build with this included and than announce this feature at the forums and mailing list asking for testers.

File: src/encoder/encoderopus.cpp [hunk 32]
```diff
@@ -0,0 +1,465 @@
...
+#include "encoder/encoderopussettings.h"
+#include "engine/sidechain/enginesidechain.h"
+#include "util/logger.h"
+
+#include "encoder/encoderopus.h"
+
+// Opus only supports 48 and 96 kHz samplerates
+constexpr int EncoderOpus::MASTER_SAMPLERATE = 48000;
+
+const char* EncoderOpus::INVALID_SAMPLERATE_MESSAGE =
```
Comment (esbrandt) [inline src/encoder/encoderopus.cpp]: The OPUS error message is hidden behind other error message (moved downwards in the screens for readability).

* When broadcasting:
The warning is displayed beneath the connection error message.
capto_capture 2019-01-11_10-39-12_am

* When recording:
  The warning is displayed beneath the recording error message, given no path is set in the recordings folder (default)
capto_capture 2019-01-11_10-38-32_am
