### ISSUE TITLE
Vinyl Control: Show Signal Quality On Skin, not working

### ISSUE THREAD

**Issue by NotYourAverageAl** [mixxxdj/mixxx#11734]
### Bug Description

The Vinyl Control option "Show Signal Quality On Skin", does not work on the latest 2.4 beta. The signal quality widget no longer shows on the spinnies when set in the preferences.

Thought it might be related to @m0dB 's GLSL work on the spinnies and I can confirm that.

Snapshot 2.4-alpha-1512-gbf1102212f works, but after [10989](https://github.com/mixxxdj/mixxx/pull/10989) it does not.

### Version

2.4-beta-48-g2cb54d9281

### OS

Windows 11

**Comment by m0dB** [comment]
Thanks, I will take a look later this week.

**Comment by ronso0** [comment]
Might as well be a regression of #11272, I'll take a look.

**Comment by ronso0** [comment]
> Might as well be a regression of ~#11272~ #11663 , I'll take a look.

Nope, it's not, VC manager is still updating from config when clicking Apply

**Comment by ronso0** [comment]
Another aspect of this bug seems to be that the vinyl signal quality is drawn in the preferences only if "Show quality in skins" is checked (+ Apply ofc). Should be drawn in the preferences regardless (as before 8aef3199f436046d7670008ca332230ab0cd0679)

Btw I was curious and started to git bisect but that's impossible due to unbuildable commits  :|
for example
```
/src/waveform/renderers/glwaveformrenderer.h:13:15: error: class ‘GLWaveformRenderer’ does not have any field named ‘WaveformRendererSignalBase’
   13 |             : WaveformRendererSignalBase(waveformWidgetRenderer)
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by m0dB** [comment]
I have this under control for the spinnies, but I need to figure out the most efficient way to do this. I could commit a temporary fix in the meantime. However, I would like to really test that it works, but I don't have a vinyl controller myself. Is there a way to emulate this? Is that just a matter of feeding an audio input with the right signal? Where do I get such a signal (all this is new to me).

I haven't investigated what is drawn (or not) in the preferences yet. Not sure that is related to my changes.

**Comment by JoergAtGithub** [comment]
You could download the Serato Control Signal and burn it to a CD: https://serato.com/controlcd/downloads?manualsanddownloads#manuals-and-download

**Comment by ronso0** [comment]
...and either use an external player, or set up an audio loopback device (output deckA -> loopback, loopback -> VC input deckB) and play the timecode with Mixxx deckA to control deckB.
When I did this the pitch was fluctuating sporadically but it was okay to test the signal quality. You can use the Balance, BitCrusher or White noise effect or whatever to emulate signal impairment.
