### PR TITLE
Library track selection tweaks

### PR DESCRIPTION
**Pull request by ronso0**
follow-up of #4177, picking bites from #3063 to improve the track selection when changing features and search queries.
* only attempt to load a saved selection state if the new search query is more specific

### CODE REVIEW

File: src/library/libraryview.h [hunk 1]
```diff
@@ -35,8 +35,9 @@ class LibraryView {
     }
     virtual void saveCurrentViewState() {
     }
-    virtual void restoreCurrentViewState() {
-    }
+    virtual bool restoreCurrentViewState() {
```
Comment (uklotzde) [inline src/library/libraryview.h:38]: Please document the meaning of the boolean return value.

File: src/library/searchqueryparser.cpp [hunk 2]
```diff
@@ -1,9 +1,14 @@
 #include "library/searchqueryparser.h"
 
+#include <QRegularExpression>
+
 #include "track/keyutils.h"
 
 constexpr char kNegatePrefix[] = "-";
 constexpr char kFuzzyPrefix[] = "~";
+// see https://stackoverflow.com/questions/1310473/regex-matching-spaces-but-not-in-strings
+const QRegularExpression kSplitRegexp = QRegularExpression(
```
Comment (uklotzde) [inline src/library/searchqueryparser.cpp:10]: kSplitIntoWordsRegexp

File: src/library/searchqueryparser.cpp [hunk 3]
```diff
@@ -271,3 +276,43 @@ std::unique_ptr<QueryNode> SearchQueryParser::parseQuery(const QString& query,
...
 }
+
+QStringList SearchQueryParser::splitQuery(const QString& query) {
+    QStringList queryWordList = query.split(kSplitRegexp, QString::SkipEmptyParts);
+    return queryWordList;
+}
+
+bool SearchQueryParser::queryIsLessSpecific(const QString& original, const QString& changed) {
+    // separate search query into tokens
+    QStringList oldList = SearchQueryParser::splitQuery(original);
```
Comment (uklotzde) [inline src/library/searchqueryparser.cpp:287]: oldList -> oldWordList

File: src/library/searchqueryparser.h [hunk 4]
```diff
@@ -19,6 +19,10 @@ class SearchQueryParser {
             const QStringList& searchColumns,
             const QString& extraFilter) const;
 
+    /// splits the query into a list of terms
+    static QStringList splitQuery(const QString& query);
```
Comment (uklotzde) [inline src/library/searchqueryparser.h:23]: splitQueryIntoWords()

File: src/widget/wtracktableview.cpp [hunk 5]
```diff
@@ -869,6 +892,26 @@ QList<TrackId> WTrackTableView::getSelectedTrackIds() const {
     return trackIds;
 }
 
+TrackId WTrackTableView::getCurrentTrackId() const {
+    QItemSelectionModel* pSelectionModel = selectionModel();
+    VERIFY_OR_DEBUG_ASSERT(pSelectionModel != nullptr) {
+        qWarning() << "No selected tracks available";
+        return TrackId();
```
Comment (uklotzde) [inline src/widget/wtracktableview.cpp:899]: You can simply use `return {}` in these cases to avoid repeating the type name over and over again. The actual type is visible in the signature above.

File: src/widget/wtracktableview.cpp [hunk 6]
```diff
@@ -892,6 +935,30 @@ void WTrackTableView::setSelectedTracks(const QList<TrackId>& trackIds) {
     }
 }
 
+bool WTrackTableView::setCurrentTrackId(const TrackId& trackId, const int column = 0) {
+    QItemSelectionModel* pSelectionModel = selectionModel();
```
Comment (uklotzde) [inline src/widget/wtracktableview.cpp:939]: This code is unneeded if pTrackModel->getTrackRows(trackId) returns an empty list. Please move it downwards.

**Review by uklotzde — CHANGES_REQUESTED** [review]

File: src/library/searchqueryparser.cpp (hunk 3 above)
Comment (ronso0) [reply src/library/searchqueryparser.cpp:287]: hehe, sure. originally it was olist > oldList > oldWordList
now that small function is super clear ;)

File: src/widget/wtracktableview.cpp (hunk 5 above)
Comment (ronso0) [reply src/widget/wtracktableview.cpp:899]: Thanks!

File: src/widget/wtracktableview.cpp (hunk 6 above)
Comment (ronso0) [reply src/widget/wtracktableview.cpp:939]: done.

File: src/library/searchqueryparser.h (hunk 4 above)
Comment (ronso0) [reply src/library/searchqueryparser.h:23]: :+1:

**Comment by ronso0** [comment]
Note: I marked it as draft because I'll rebase -- still wanted to test and work out some details.
Thanks for the early review though!

File: src/library/searchqueryparser.cpp (hunk 2 above)
Comment (ronso0) [reply src/library/searchqueryparser.cpp]: done.

File: src/library/libraryview.h (hunk 1 above)
Comment (ronso0) [reply src/library/libraryview.h:38]: I copied the description from src/widget/wlibrarytableview.h

**Comment by ronso0** [comment]
Actually, this is it.
initially I was planning to pick `save TrackIds instead of index if possible` from 7b9e4055998de90f05fe87e71e9acd0d6d5616c9, too, but this state here is sufficient for now, so I'll resume some other PRs instead.

**Comment by poelzi** [comment]
Saving only indexes is super annoying, thats why I implemented the IDs. I often use a filter like
"genre played:0" and play some stuff. If tracks are playing and you are in the history for example and switch back, causes the wrong selection. So, the new code tries to save trackids if the view supports those.

**Comment by ronso0** [comment]
Okay, now this works also if an invalid (invisible) column is passed to setCurrentTrack() in case it is invoked from somewhere else then onSearch().

File: src/widget/wtracktableview.cpp [hunk 7]
```diff
@@ -904,6 +947,34 @@ void WTrackTableView::setSelectedTracks(const QList<TrackId>& trackIds) {
     }
 }
 
+bool WTrackTableView::setCurrentTrackId(const TrackId& trackId, const int column = 0) {
```
Comment (uklotzde) [inline src/widget/wtracktableview.cpp:950]: Default argument in implementation? Please also remove the `const` keyword.

**Review by uklotzde — CHANGES_REQUESTED** [review]

**Comment by ronso0** [comment]
@uklotzde 
I  will squash the last --fixup commit after the final LGTM

File: src/widget/wtracktableview.cpp (hunk 7 above)
Comment (ronso0) [reply src/widget/wtracktableview.cpp]: Oh. Fixed

**Review by uklotzde — APPROVED** [review]
I cannot promise that there are no regression. But code looks good, so let's move on. Thank you! LGTM

**Comment by uklotzde** [comment]
However the local build with Qt 5.15 failed:

```
/home/uk/volumes/Build/cpp/mixxx/src/library/searchqueryparser.cpp:396:77: error: 'SkipEmptyParts' is deprecated [-Werror,-Wdeprecated-declarations]
    QStringList queryWordList = query.split(kSplitIntoWordsRegexp, QString::SkipEmptyParts);
                                                                            ^
/usr/include/qt5/QtCore/qstring.h:605:24: note: 'SkipEmptyParts' has been explicitly marked deprecated here
        SkipEmptyParts Q_DECL_ENUMERATOR_DEPRECATED
                       ^
/usr/include/qt5/QtCore/qcompilerdetection.h:1160:40: note: expanded from macro 'Q_DECL_ENUMERATOR_DEPRECATED'
#  define Q_DECL_ENUMERATOR_DEPRECATED Q_DECL_DEPRECATED
                                       ^
/usr/include/qt5/QtCore/qcompilerdetection.h:227:45: note: expanded from macro 'Q_DECL_DEPRECATED'
#  define Q_DECL_DEPRECATED __attribute__ ((__deprecated__))
                                            ^
/home/uk/volumes/Build/cpp/mixxx/src/library/searchqueryparser.cpp:396:39: error: 'split' is deprecated: Use Qt::SplitBehavior variant instead [-Werror,-Wdeprecated-declarations]
    QStringList queryWordList = query.split(kSplitIntoWordsRegexp, QString::SkipEmptyParts);
                                      ^
/usr/include/qt5/QtCore/qstring.h:627:23: note: 'split' has been explicitly marked deprecated here
    Q_REQUIRED_RESULT QT_DEPRECATED_VERSION_X_5_15("Use Qt::SplitBehavior variant instead")
                      ^
/usr/include/qt5/QtCore/qglobal.h:374:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_15'
# define QT_DEPRECATED_VERSION_X_5_15(text) QT_DEPRECATED_X(text)
                                            ^
/usr/include/qt5/QtCore/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/usr/include/qt5/QtCore/qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
2 errors generated.
```
