### PR TITLE
Add controller support for Pioneer DDJ-400

### PR DESCRIPTION
**Pull request by WarkerAnhaltRanger**
This is a initial Support for the Pioneer DDJ-400
Testers are welcome!
Working:
                * Mixer Section (Faders, EQ, Filter, Gain, Cue)
                * Browsing and loading + Waveform zoom (shift)
                * Jogwheels, Scratching, Bending
                * cycle Temporange
                * Beat Sync
                * Beat Loop Mode
                * Sampler Mode
                * Beatjump mode
            
Testing:
                * Keyboard Mode (check pitch value)
                * Keyshift Mode (check pitch value
                * Hot Cue Mode (including loops)
                * Loop Section: Loop in / Out + Adjust, Call, Double, Half
                * Effect Section (Beat FX left + Right - select the Effect Slot of FX3 (not Effect BPM))
                * Output (lights)

Partially:
                * PAD FX (only slots A-H, Q-P)
                * Effect Section (without Beat FX left + Right - no equivalent function found)

Not working/implemented:
                * Channel & Crossfader Start

### CODE REVIEW

**Comment by WarkerAnhaltRanger** [comment]
* Forum: https://mixxx.org/forums/viewtopic.php?f=7&t=12113
* Wiki: https://www.mixxx.org/wiki/doku.php/pioneer_ddj-400

**Comment by WarkerAnhaltRanger** [comment]
- [ ] implement blinking pad when playing sample or fx
- [ ] implement blinking Loop in and out when loop is activated

**Comment by WarkerAnhaltRanger** [comment]
could someone review this?

**Comment by uklotzde** [comment]
Thank you for providing this mapping! We need the permission to distribute your contributions by signing the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ)

I have some initial technical remarks:
- Please add a detailed description of the mapping to the wiki, example: https://www.mixxx.org/wiki/doku.php/roland_dj-505
- The use of whitespace in the JS file is very inconsistent. Please consider reformatting it to improve readability.
- I would recommend to run JSHint on the JS file. This should result in some recommendations like using ===/!== instead of ==/!=.

And please be patient if you don't get feedback within a few hours. We are all volunteers that spend their rare spare time for this project.

**Comment by WarkerAnhaltRanger** [comment]
Thank you for your Feedback.
Signed the agreement.
Going to document mapping in the wiki soon. Basically I implemented the same functions as in the User manual for Rekordbox. 
JSHint did not state any problems besides that hotcuePad in keyboardModeEnabledOutput was already defined. Fixed that.
I'll check the format.

**Comment by nschloe** [comment]
I've tried this PR with my DDJ-400 and found it _mostly_ working. At first glance, things not working:

 * Track selector scrolls fine, but doesn't load track on click.
 * Pressing  any of `HOT CUE`, `BEAT LOOP`, `BEST JUMP`, `SAMPLER` results in the error message
   `Uncaught exception at line 1 in passed code: TypeError: Result of expression '(PioneerDDJ400.modeChange)' [undefined] is not a function.`

**Comment by uklotzde** [comment]
It's ok to add missing features later, but at least the undefined access errors should be fixed.

**Comment by uklotzde** [comment]
@nschloe Thanks for testing!

**Comment by WarkerAnhaltRanger** [comment]
> I've tried this PR with my DDJ-400 and found it _mostly_ working. At first glance, things not working:

Thank you for testing!

> 
>     * Track selector scrolls fine, but doesn't load track on click.
> 
The press on the rotary selector cycles the focus between the Library Folders and the Tracks. (same as Rekordbox). You load the Track using the "LOAD" button 

>     * Pressing  any of `HOT CUE`, `BEAT LOOP`, `BEST JUMP`, `SAMPLER` results in the error message
>       `Uncaught exception at line 1 in passed code: TypeError: Result of expression '(PioneerDDJ400.modeChange)' [undefined] is not a function.`
I accidently forgot to remove the reference for the removed modeChange function in the XML File.
I updated the XML.

**Comment by nschloe** [comment]
> The press on the rotary selector cycles the focus between the Library Folders and the Tracks. (same as Rekordbox). You load the Track using the "LOAD" button

Perfect, that works.

> I updated the XML.

Confirmed fixed.

**Comment by WarkerAnhaltRanger** [comment]
I updated the Wikipage.
The current implementation is covered.
Also I made a Mistake with the .gitignore file (and I don't know how to revert this). The .gitignore File should not be merged.

**Comment by nschloe** [comment]
> The .gitignore File should not be merged.

Simply `git revert` the respective commit.

**Comment by nschloe** [comment]
Btw, I've been using this PR succussfully with my DDJ-400 for a while now. How can I help getting this merged?

**Comment by jsBrian** [comment]
I've been using this branch with my DDJ-400 on Ubuntu 18.04.  Works for me as well.

**Comment by WarkerAnhaltRanger** [comment]
Is there something missing or wrong with the code? How can I get this merged into mixxx?

**Comment by unlimited67g** [comment]
Hello all,

first thank you for your work.

I'm quite a noob.
Trying to make my DD 400 work with linux mint 19.2 cinnamon and Mixxx 2.2 . 

I'm putting the .xml and .js files in the controllers folder but get this issue :

`
There was a problem parsing the XML file /usr/share/mixxx/controllers/Pioneer-DDJ-400.midi.xml.

unexpected character at line 44, column 89`

Any help welcome !

thanks again ;)

**Comment by uklotzde** [comment]
@WarkerAnhaltRanger Please _interactively rebase_ your branch and remove all unrelated changes that affect files other than the added .xml and the .js file.

**Comment by uklotzde** [comment]
@unlimited67g Please verify that you downloaded the actual contents of the files (_Raw_) and not some HTML view from Github. I don't spot any errors on line 44 in the .xml file.

**Comment by Be-ing** [comment]
Sorry for the delay. I'll review this today or tomorrow.

**Comment by Be-ing** [comment]
Unless you have mapped new features for Mixxx 2.3, please change the target branch of the pull request to 2.2 and rebase on the 2.2 branch. That way this can be included in Mixxx 2.2.3.

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 1]
```diff
@@ -0,0 +1,718 @@
...
+        engine.setValue(group, 'loop_out', 1);
+    }
+};
+
+// START BEAT FX
+
+PioneerDDJ400.numFxSlots = 3;
+
+Object.defineProperty(PioneerDDJ400, 'selectedFxSlot', {
+    get: function() {
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: This works with the ancient QtScript interpreter? I remember trying this years ago and couldn't get it to work.

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 2]
```diff
@@ -0,0 +1,718 @@
...
+PioneerDDJ400.beatFxChannel = ignoreRelease(function(_channel, control, _value, _status, group) {
+    const enableChannel1 = control === 0x10 || control === 0x14;
+    const enableChannel2 = control === 0x11 || control === 0x14;
+
+    engine.setValue(group, 'group_[Channel1]_enable', enableChannel1);
+    engine.setValue(group, 'group_[Channel2]_enable', enableChannel2);
+});
+
+PioneerDDJ400.padFxBelowPressed = ignoreRelease(function(channel, control, value, status, group) {
+    const groupAbove = group.replace(/\[EffectRack1_EffectUnit(\d+)_Effect(\d+)]/, function(all, unit, effect) {
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: `const` is not actually supported by the interpreter; that it happens to work is only a coincidence. Please change all `const`s to `var` to avoid confusion.

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 3]
```diff
@@ -0,0 +1,718 @@
...
+        const effectAbove = parseInt(effect, 10) - 4;
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: I don't think the `10` parameter for `parseInt` is needed.

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 4]
```diff
@@ -0,0 +1,718 @@
...
+    points.push( engine.getValue(group, 'cue_point'));
+    points.push( engine.getValue(group, 'loop_start_position'));
+    points.push( engine.getValue(group, 'loop_end_position'));
+    points.sort(sortAsc); // sort asc
+
+    return points;
+};
+
+PioneerDDJ400.cueLoopCallLeft = function(_channel, _control, value, _status, group){
+    if(value == 0) return; // ignore release
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: Please do not use one line `if` statements.

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 5]
```diff
@@ -0,0 +1,718 @@
...
+
+    const loop_on = engine.getValue(group, 'loop_enabled');
+    if (loop_on){
+        // loop halve
+        engine.setValue(group, 'loop_scale', 0.5);
+    }
+    else{
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: Move this to the previous line: `} else {`

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 6]
```diff
@@ -0,0 +1,718 @@
...
+    points.sort(sortAsc); // sort asc
+
+    return points;
+};
+
+PioneerDDJ400.cueLoopCallLeft = function(_channel, _control, value, _status, group){
+    if(value == 0) return; // ignore release
+
+    const loop_on = engine.getValue(group, 'loop_enabled');
+    if (loop_on){
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: space after `)`:
`if (loop_on) {`

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 7]
```diff
@@ -0,0 +1,718 @@
...
+        var newPosition = currentPosition;
+
+        for(var i = 1; i <= points.length; i++){
+            if(i == points.length || points[i] >= currentPosition * trackSamples){
+                newPosition = points[i-1] / trackSamples;
+                break;
+            }
+        }
+        //engine.setValue(group, 'loop_in_goto', 1);
+        engine.setValue(group, 'playposition', newPosition);
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: I do not understand the purpose of this. This controller has hotcue buttons, so what does this add?

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 8]
```diff
@@ -0,0 +1,718 @@
...
+};
+
+PioneerDDJ400.jogTurn = function(channel, _control, value, _status, group) {
+    const deckNum = channel + 1;
+    // wheel center at 64; <64 rew >64 fwd
+    var newVal = value - 64;
+
+    // loop_in / out adjust
+    const loopEnabled = engine.getValue(group, 'loop_enabled');
+    if(loopEnabled > 0){
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: spaces around parentheses: `if (loopEnabled > 0) {`

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 9]
```diff
@@ -0,0 +1,718 @@
...
+        engine.setValue(group, 'loop_in_goto', 1);
+        engine.setValue(group, 'reloop_toggle', 1);
+        // This is a hack, TODO find a command like loop_in_goto_and_play
+        if(engine.getValue(group, 'loop_enabled') == 0){
+            engine.setValue(group, 'reloop_toggle', 1);
+        }
+        return;
+    }
+
+    // save playing loop on hotcue pad
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: I think this hack should be removed. What is the point of saving a loop if it is lost when Mixxx shuts down? We are currently working on adding this feature to Mixxx in #2194. If you would like to help implement and/or test that feature, that would be great!

File: res/controllers/Pioneer-DDJ-400-script.js [hunk 10]
```diff
@@ -0,0 +1,718 @@
...
+    }
+};
+
+// START BEAT FX
+
+PioneerDDJ400.numFxSlots = 3;
+
+Object.defineProperty(PioneerDDJ400, 'selectedFxSlot', {
+    get: function() {
+        return engine.getValue('[EffectRack1_EffectUnit3]', 'focused_effect');
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400-script.js]: Why does this use EffectUnit 3? This requires the user to show all 4 effect units on screen even though the controller can only manipulate one of them. Wouldn't it make more sense to map the controller to EffectUnit 1?

File: res/controllers/Pioneer-DDJ-400.midi.xml [hunk 11]
```diff
@@ -0,0 +1,4688 @@
...
+                <status>0x90</status>
+                <midino>0x4D</midino>
+                <options>
+                    <Normal/>
+                </options>
+            </control>
+            <control>
+                <description>RELOOP/EXIT +SHIFT (DECK1) - press - Active loop on/off</description>
+                <group>[Channel1]</group>
+                <key>reloop_toggle</key> <!-- TODO Check if correct -->
```
Comment (Be-ing) [inline res/controllers/Pioneer-DDJ-400.midi.xml]: I suggest mapping this to `reloop_andstop`

**Review by Be-ing — CHANGES_REQUESTED** [review]
Some preliminary comments; I haven't read through the whole wiki or script yet. There are lots of little style issues. Please review the [JS coding conventions](https://mixxx.org/wiki/doku.php/contributing_mappings#coding_conventions_for_javascript)

**Comment by unlimited67g** [comment]
> @unlimited67g Please verify that you downloaded the actual contents of the files (_Raw_) and not some HTML view from Github. I don't spot any errors on line 44 in the .xml file.

Hello,

thank you i did that and no more of this error !

But when i plug the controller and the open mixxx and then enable the midi controller in the preferences, i can't control anything with the controller...
Am i missing something (again..) ?

Thanks

**Comment by WarkerAnhaltRanger** [comment]
I'm sorry. I'm afraid I can't finish this pull request since my RL took over.
Maybe someone else could finish this?

**Comment by Be-ing** [comment]
That's okay, thank you for communicating that. @nschloe or @jsBrian would you like to continue with this? You can start by making a branch on your fork from this branch and making a new pull request.

**Comment by nschloe** [comment]
See #2312.
