### PR TITLE
Added new method HidController::send_feature_report

### PR DESCRIPTION
**Pull request by JoergAtGithub**
Made the method hid_send_feature_report from HIDAPI available to controller mappings.
This generic USB HID "Set Reports (Feature)" functionality is needed to set the NI Traktor Z2 in a mode, where it accepts the bulk HID reports for LED control. See also: https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/Traktor.20Kontrol.20Z2
The USBlyzer dump looks now like this:
grafik

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Do I need to document this new API method anywhere?

**Comment by Be-ing** [comment]
This is a new feature so it should go to the master branch.

File: src/controllers/hid/hidcontroller.h [hunk 1]
```diff
@@ -50,6 +50,8 @@ class HidController final : public Controller {
 
   protected:
     Q_INVOKABLE void send(QList<int> data, unsigned int length, unsigned int reportID = 0);
+    Q_INVOKABLE void send_feature_report(
+            QList<int> data, unsigned int length, unsigned int reportID = 0);
```
Comment (Be-ing) [inline src/controllers/hid/hidcontroller.h:54]: 1. This is specific to HidController, so it should be private.
2. Rename to `sendFeatureReport` for consistency
3. Remove useless `length` parameter.
4. I think this can accept a QByteArray as input so I don't think there's a need to separate this into 2 functions.

**Comment by Be-ing** [comment]
> Do I need to document this new API method anywhere?

https://github.com/mixxxdj/mixxx/wiki/hid%20mapping#sending-data-to-the-controller

File: src/controllers/hid/hidcontroller.h (hunk 1 above)
Comment (Swiftb0y) [reply src/controllers/hid/hidcontroller.h:54]: I'm not sure if QtScript can handle QByteArrays since there are no ArrayBuffers/TypedArrays in the ES3-like environment.

Comment (Be-ing) [reply src/controllers/hid/hidcontroller.h:54]: This should be merged to master so that doesn't matter.

File: src/controllers/hid/hidcontroller.cpp [hunk 2]
```diff
@@ -277,6 +277,38 @@ void HidController::send(QByteArray data, unsigned int reportID) {
     data.prepend(reportID);
 
     int result = hid_write(m_pHidDevice, (unsigned char*)data.constData(), data.size());
+    if (result == -1) {
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:280]: should this be a constant (constexpr in anonymous namespace)?

File: src/controllers/hid/hidcontroller.cpp [hunk 3]
```diff
@@ -277,6 +277,38 @@ void HidController::send(QByteArray data, unsigned int reportID) {
...
+        }
+    } else {
+        controllerDebug(result << "bytes sent to" << getName()
+                               << "serial #" << hid_serial
+                               << "(including report ID of" << reportID << ")");
+    }
+}
+
+void HidController::send_feature_report(
+        QList<int> data, unsigned int length, unsigned int reportID) {
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:297]:
```suggestion
        const QList<int>& data, unsigned int reportID) {
```

File: src/controllers/hid/hidcontroller.cpp [hunk 4]
```diff
@@ -277,6 +277,38 @@ void HidController::send(QByteArray data, unsigned int reportID) {
...
+    Q_UNUSED(length);
+    QByteArray temp;
+    foreach (int datum, data) {
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:300]:
```suggestion
    for (const int datum : data) {
```

File: src/controllers/hid/hidcontroller.cpp [hunk 5]
```diff
@@ -277,6 +277,38 @@ void HidController::send(QByteArray data, unsigned int reportID) {
...
+    }
+    send_feature_report(temp, reportID);
+}
+
+void HidController::send_feature_report(QByteArray data, unsigned int reportID) {
+    // Append the Report ID to the beginning of data[] per the API..
+    data.prepend(reportID);
+
+    int result = hid_send_feature_report(
+            m_pHidDevice, (unsigned char*)data.constData(), data.size());
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:311]:
```suggestion
            m_pHidDevice, static_cast<unsigned char*>data.constData(), data.size());
```

File: src/controllers/hid/hidcontroller.cpp [hunk 6]
```diff
@@ -277,6 +277,38 @@ void HidController::send(QByteArray data, unsigned int reportID) {
...
+    QByteArray temp;
+    foreach (int datum, data) {
+        temp.append(datum);
+    }
+    send_feature_report(temp, reportID);
+}
+
+void HidController::send_feature_report(QByteArray data, unsigned int reportID) {
+    // Append the Report ID to the beginning of data[] per the API..
+    data.prepend(reportID);
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:308]: Won't this modify the original data array?

**Review by Holzhaus — CHANGES_REQUESTED** [review]

File: src/controllers/hid/hidcontroller.cpp (hunk 2 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp:280]: I didn't changed the code of HidController::send

File: src/controllers/hid/hidcontroller.h (hunk 1 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h]: 1.) I tried to make the method private, but then it was no longer visible in the controller mapping
2.) Renamed the function as suggested
3.) Removed the useless length parameter
4.) I removed the second function, but the call from the controller script works only with QList<int> not with QByteArray. Therefore the remaining function has the QList<int> argument.

File: src/controllers/hid/hidcontroller.cpp (hunk 3 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: length argument is removed now

File: src/controllers/hid/hidcontroller.h (hunk 1 above)
Comment (Swiftb0y) [reply src/controllers/hid/hidcontroller.h]: > This should be merged to master so that doesn't matter.

Right, then I'd argue we should even use the more general API spec where we mandate the reportID to be included in the buffer itself instead of being passed separately just of it to be prepended in the C++ later.

File: src/controllers/hid/hidcontroller.cpp (hunk 2 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp:285]: I think the diff is visualizing this incorrect. I added a new method after HidController::send with mostly the same content. The diff marks my code as unchanged and the original code as changed.

File: src/controllers/hid/hidcontroller.cpp (hunk 3 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Changed to const now

File: src/controllers/hid/hidcontroller.cpp (hunk 4 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Changed to cons for loop as suggested

File: src/controllers/hid/hidcontroller.cpp (hunk 5 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: I tried this, but I got the following compiler failure:
[CXX] src\controllers\hid\hidcontroller.cpp
hidcontroller.cpp
src\controllers\hid\hidcontroller.cpp(312): error C2061: Syntaxfehler: Bezeichner "dataArray"
src\controllers\hid\hidcontroller.cpp(312): error C2146: Syntaxfehler: Fehlendes "(" vor Bezeichner "dataArray"
src\controllers\hid\hidcontroller.cpp(311): error C2660: "hid_send_feature_report": Funktion akzeptiert keine 1 Argumente
lib\hidapi\hidapi\hidapi.h(296): note: Siehe Deklaration von "hid_send_feature_report"
src\controllers\hid\hidcontroller.cpp(312): error C3927: "->": Ein nachstehender Rückgabetyp ist nach einem Nichtfunktionsdeklarator nicht zulässig.
src\controllers\hid\hidcontroller.cpp(312): error C3484: Syntaxfehler: "->" wird vor dem Rückgabetyp erwartet.
src\controllers\hid\hidcontroller.cpp(312): error C3613: Rückgabetyp nach '"->" (Annahme: "int") fehlt
src\controllers\hid\hidcontroller.cpp(312): error C2371: "dataArray": Neudefinition; unterschiedliche Basistypen
src\controllers\hid\hidcontroller.cpp(303): note: Siehe Deklaration von "dataArray"
src\controllers\hid\hidcontroller.cpp(312): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "size"
src\controllers\hid\hidcontroller.cpp(312): error C3861: "size": Bezeichner wurde nicht gefunden.
src\controllers\hid\hidcontroller.cpp(312): error C2059: Syntaxfehler: ")"
scons: *** [win64_build\src\controllers\hid\hidcontroller.obj] Error 2

File: src/controllers/hid/hidcontroller.cpp (hunk 6 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: I copied this code from the very similar method HidController::send and it sent what I expected. See the screenshot of the USB communication above. Now this data array is an internal variable of the method, therefore it shouldn't harm any code outside.

File: src/controllers/hid/hidcontroller.h [hunk 7]
```diff
@@ -65,6 +65,7 @@ class HidController final : public Controller {
     // 0x0.
     void sendBytes(const QByteArray& data) override;
     void sendBytesReport(QByteArray data, unsigned int reportID);
+	void sendFeatureReport(const QList<int>& dataList, unsigned int);
```
Comment (Be-ing) [inline src/controllers/hid/hidcontroller.h:68]:
```suggestion
    void sendFeatureReport(const QList<int>& dataList, unsigned int);
```
Use spaces, not tabs

File: src/controllers/hid/hidcontroller.h [hunk 8]
```diff
@@ -112,8 +113,13 @@ class HidControllerJSProxy : public ControllerJSProxy {
         m_pHidController->sendReport(data, length, reportID);
     }
 
+	Q_INVOKABLE void sendFeatureReport(
+            const QList<int>& dataList, unsigned int reportID) {
```
Comment (Be-ing) [inline src/controllers/hid/hidcontroller.h:117]: Please try using QByteArray again now that this is based on master.

File: src/controllers/hid/hidcontroller.h (hunk 7 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h]: Done

File: src/controllers/hid/hidcontroller.cpp [hunk 9]
```diff
@@ -298,6 +298,34 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
+	
+    // Append the Report ID to the beginning of dataArray[] per the API..
+    dataArray.prepend(reportID);
+
+    int result = hid_send_feature_report(
+            m_pHidDevice, (unsigned char*)dataArray.constData(), dataArray.size());
+    if (result == -1) {
+        if (ControllerDebug::enabled()) {
+            qWarning() << "Unable to send data to" << getName()
+                       << "serial #" << hid_serial << ":"
```
Comment (ywwg) [inline src/controllers/hid/hidcontroller.cpp:316]: Only removing the serial number in non-debug mode is not significant enough to justify having these two branches.  Either always send a message, or only send a message in debug mode.  I'd prefer we only send this message in debug mode.  It will probably only be useful during development or if the controller isn't working, and in both cases the user will want to run with debugging enabled in order to diagnose the problem.

File: src/controllers/hid/hidcontroller.h [hunk 10]
```diff
@@ -112,8 +113,13 @@ class HidControllerJSProxy : public ControllerJSProxy {
         m_pHidController->sendReport(data, length, reportID);
     }
 
+	Q_INVOKABLE void sendFeatureReport(
```
Comment (Be-ing) [inline src/controllers/hid/hidcontroller.h:116]: Also here, please use spaces consistently

File: src/controllers/hid/hidcontroller.cpp [hunk 11]
```diff
@@ -298,6 +298,34 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
 
+void HidController::sendFeatureReport(
+        const QList<int>& dataList, unsigned int reportID) {
+    QByteArray dataArray;
+    for (const int datum: dataList) {
+        dataArray.append(datum);
+    }
+	
+    // Append the Report ID to the beginning of dataArray[] per the API..
+    dataArray.prepend(reportID);
```
Comment (ywwg) [inline src/controllers/hid/hidcontroller.cpp:309]: if you start by appending the reportID and then append the datalist, it'll be a little faster and easier to read

File: src/controllers/hid/hidcontroller.h [hunk 12]
```diff
@@ -112,8 +113,13 @@ class HidControllerJSProxy : public ControllerJSProxy {
...
+            const QList<int>& dataList, unsigned int reportID) {
+        m_pHidController->sendFeatureReport(dataList, reportID);
+    }
+
   private:
     HidController* m_pHidController;
 };
 
-#endif
+#endif
```
Comment (ywwg) [inline src/controllers/hid/hidcontroller.h:125]: files need to end in a newline

File: src/controllers/hid/hidcontroller.h (hunk 10 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h]: Done

**Comment by Be-ing** [comment]
> I'd argue we should even use the more general API spec where we mandate the reportID to be included in the buffer itself instead of being passed separately just of it to be prepended in the C++ later.

Hmm, we could do this. Or we could make the report ID the first argument so it can't be omitted by the script. However, that could get confusing because `controller.send` has the arguments the opposite way around. So I think requiring the script to provide the report ID in the buffer would be better.

File: src/controllers/hid/hidcontroller.cpp [hunk 13]
```diff
@@ -298,6 +298,34 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
+            m_pHidDevice, (unsigned char*)dataArray.constData(), dataArray.size());
+    if (result == -1) {
+        if (ControllerDebug::enabled()) {
+            qWarning() << "Unable to send data to" << getName()
+                       << "serial #" << hid_serial << ":"
+                       << safeDecodeWideString(hid_error(m_pHidDevice), 512);
+        } else {
+            qWarning() << "Unable to send data to" << getName() << ":"
+                       << safeDecodeWideString(hid_error(m_pHidDevice), 512);
+        }
```
Comment (ywwg) [inline src/controllers/hid/hidcontroller.cpp:321]: I prefer:

```
if (error case) {
  // handle error;
  return;
}

// success case.
```

This reduces the amount of if/else indentation.

**Review by ywwg — CHANGES_REQUESTED** [review]

File: src/controllers/hid/hidcontroller.cpp (hunk 9 above)
Comment (Be-ing) [reply src/controllers/hid/hidcontroller.cpp:316]: On further thought, I think a warning of a script failure should always be shown regardless of ControllerDebug::enabled

Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp:316]: I used excatly the code as for HidController::sendBytesReport 20 lines above. Do you prefer two different implementations for the same type of wrapper code?

File: src/controllers/hid/hidcontroller.h (hunk 12 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h]: Done

File: src/controllers/hid/hidcontroller.h (hunk 8 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h:117]: I tried again, but it doesn'tcompile:
[CXX] src\controllers\hid\hidcontroller.cpp
hidcontroller.cpp
src\controllers\hid\hidcontroller.cpp(305): error C2663: "QByteArray::prepend": für 5 Überladung(en) gibt es keine zulässige Konvertierung für den this-Zeiger
scons: *** [win64_build\src\controllers\hid\hidcontroller.obj] Error 2
scons: building terminated because of errors.
==============================

Building Mixxx failed.

File: src/controllers/hid/hidcontroller.cpp (hunk 5 above)
Comment (Holzhaus) [reply src/controllers/hid/hidcontroller.cpp]: Forgot the braces after `>` :D

Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Only a opening brace? Isn't a closing brace needed anywhere too?

Comment (Holzhaus) [reply src/controllers/hid/hidcontroller.cpp]: Yes, after `data.constData()`.

**Comment by JoergAtGithub** [comment]
It seems that the HID API changed incompatible between 2.3 and master. The old command controller.send doesn't work anymore in my controller mapping. It just sends the report ID and than all data 0x00.
This happens at least with the debugLights code, which seems to be used in various HID mappings. My implementation is here: https://github.com/mixxxdj/mixxx/blob/11f97d696451758ccad6e432d662168aae8954a2/res/controllers/Traktor.Kontrol-Z2-hid-scripts.js#L579 but I took this code from @ywwg 
I could imagine that there happend a change, which broke the type safe data handling of this API, because it works how it's used in common-hid-packet-parser.js

File: src/controllers/hid/hidcontroller.cpp (hunk 5 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: This does not work:
[CXX] src\controllers\hid\hidcontroller.cpp
hidcontroller.cpp
src\controllers\hid\hidcontroller.cpp(312): error C2440: "static_cast": "const char *" kann nicht in "unsigned char *" konvertiert werden
src\controllers\hid\hidcontroller.cpp(312): note: Die Typen, auf die verwiesen wird, sind nicht verknüpft; die Konvertierung erfordert einen reinterpret_cast-Op
erator oder eine Typumwandlung im C- oder Funktionsformat.
src\controllers\hid\hidcontroller.cpp(311): error C2660: "hid_send_feature_report": Funktion akzeptiert keine 2 Argumente
lib\hidapi\hidapi\hidapi.h(296): note: Siehe Deklaration von "hid_send_feature_report"
scons: *** [win64_build\src\controllers\hid\hidcontroller.obj] Error 2
scons: building terminated because of errors.

Why not keep the proven code from the .send method?

File: src/controllers/hid/hidcontroller.cpp (hunk 11 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp:309]: In my opinion it's better, to have he same order of arguments for the mostly identical API methods controller.send and controller.sendFeatureReport
The controller.sendFeatureReport method will be rarely used (usually once in the .int section only), while the existing controller.send method will be used often accross the code. If performance is an issue, than controller.send needs to be changed.

File: src/controllers/hid/hidcontroller.cpp (hunk 5 above)
Comment (Holzhaus) [reply src/controllers/hid/hidcontroller.cpp]: We shouldn't use c-style casts for that exact reason. It hides that these type are incompatible and this cast actually reinterprets that data. We need reinterpret_cast here.

Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: reinterpret_cast<const unsigned char*>(dataArray.constData()) works

File: src/controllers/hid/hidcontroller.cpp (hunk 9 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Warning message is now always print, independent of ControllerDebug::enabled()

File: src/controllers/hid/hidcontroller.cpp (hunk 13 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Done

File: src/controllers/hid/hidcontroller.h [hunk 14]
```diff
@@ -65,6 +65,7 @@ class HidController final : public Controller {
     // 0x0.
     void sendBytes(const QByteArray& data) override;
     void sendBytesReport(QByteArray data, unsigned int reportID);
+    void sendFeatureReport(const QList<int>& dataList, unsigned int);
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.h:68]:
```suggestion
    void sendFeatureReport(const QList<int>& dataList, unsigned int reportID);
```

File: src/controllers/hid/hidcontroller.cpp [hunk 15]
```diff
@@ -293,8 +293,32 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
+    // Append the Report ID to the beginning of dataArray[] per the API..
+    dataArray.prepend(reportID);
+
+    int result = hid_send_feature_report(m_pHidDevice,
+            reinterpret_cast<const unsigned char*>(dataArray.constData()),
+            dataArray.size());
+    if (result == -1) {
+        qWarning() << "sendFeatureReport is unable to send data to" << getName()
+                   << "serial #" << hid_serial << ":"
+                   << safeDecodeWideString(hid_error(m_pHidDevice), 512);
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:317]: Can we make 512 a constexpr in the anonymouse namespace?

File: src/controllers/hid/hidcontroller.h (hunk 14 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.h]: Done

File: src/controllers/hid/hidcontroller.cpp (hunk 15 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp:317]: Sorry, I don't know how to do this. Isn't this the length of an error message, which isn't known at compile time?

File: src/controllers/hid/hidcontroller.cpp [hunk 16]
```diff
@@ -293,8 +293,32 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
+
+void HidController::sendFeatureReport(
+        const QList<int>& dataList, unsigned int reportID) {
+    QByteArray dataArray;
+    for (const int datum : dataList) {
+        dataArray.append(datum);
+    }
+
+    // Append the Report ID to the beginning of dataArray[] per the API..
+    dataArray.prepend(reportID);
```
Comment (uklotzde) [inline src/controllers/hid/hidcontroller.cpp:309]: Prepending doesn't make sense here, it requires reshuffling the contents of QByteArray. Append everything in order.

File: src/controllers/hid/hidcontroller.cpp [hunk 17]
```diff
@@ -293,8 +293,32 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
-                 << "serial #" << hid_serial
-                 << "(including report ID of" << reportID << ")");
+                               << "serial #" << hid_serial
+                               << "(including report ID of" << reportID << ")");
+    }
+}
+
+void HidController::sendFeatureReport(
+        const QList<int>& dataList, unsigned int reportID) {
+    QByteArray dataArray;
```
Comment (uklotzde) [inline src/controllers/hid/hidcontroller.cpp:303]: The resulting size of the array is known in advance, i.e. `1 + dataList.size()`. Use `reserve()` before appending anything.

**Review by uklotzde — CHANGES_REQUESTED** [review]

**Comment by uklotzde** [comment]
Before merging any code we also need your consent by signing the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ).

File: src/controllers/hid/hidcontroller.cpp (hunk 16 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Done

File: src/controllers/hid/hidcontroller.cpp (hunk 17 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Done

**Comment by JoergAtGithub** [comment]
> 
> 
> Before merging any code we also need your consent by signing the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ).

Signed

File: src/controllers/hid/hidcontroller.cpp (hunk 11 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: After a further comment from uklotzde I understood what you really meant here. Sorry, my first answer was false. I changed the code.

File: src/controllers/hid/hidcontroller.cpp (hunk 15 above)
Comment (uklotzde) [reply src/controllers/hid/hidcontroller.cpp:319]: The literal `512` is used repeatedly in the HID code. I suggest to leave it as is to not complicate this PR. Should be fixed when refactoring HidController.

@Holzhaus The `max_length` parameter is always set to 512 so safeDecodeWideString() doesn't need to not expose it. It could later be used as a default value for this parameter.

**Comment by JoergAtGithub** [comment]
Is there anything else, I need to do, to get this PR merged?

**Review by uklotzde — APPROVED** [review]

**Comment by uklotzde** [comment]
Ping @ywwg @Holzhaus

**Comment by Be-ing** [comment]
https://github.com/mixxxdj/mixxx/pull/3051#issuecomment-683428405 has not been addressed

**Comment by JoergAtGithub** [comment]
If it's the common opinion, that the method HidController::send_feature_report should have the Report ID at the begining while the nearly identical method HidController::send has it at the end, I will change it!
But my personal opinion is, that such an inconsistent order of arguments in one and the same API, is at least weird, if not a broken.

**Comment by uklotzde** [comment]
> If it's the common opinion, that the method HidController::send_feature_report should have the Report ID at the begining while the nearly identical method HidController::send has it at the end, I will change it!
> But my personal opinion is, that such an inconsistent order of arguments in one and the same API, is at least weird, if not a broken.

I agree with that opinion. Either change all signatures or mimic the old style, even if it is considered inappropriate. Consistency is key.

**Comment by Be-ing** [comment]
How about let's make this new function fit with the existing `controller.send` API, then in the new controller system we can make a separate HIDControllerJSProxy class with different function signatures? @Swiftb0y what do you think?

File: src/controllers/hid/hidcontroller.cpp [hunk 18]
```diff
@@ -293,8 +293,34 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
...
+    dataArray.reserve(1 + dataList.size());
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp:304]: What is `1`? Can you make it a named constexpr in the anonymous namespace?

File: src/controllers/hid/hidcontroller.cpp [hunk 19]
```diff
@@ -298,10 +298,16 @@ void HidController::sendBytesReport(QByteArray data, unsigned int reportID) {
     }
 }
 
+
+namespace
+{
+    constexpr unsigned int sizeOfReportID = 1;  // Size of an USB HID Report ID is always one byte
+}
```
Comment (Holzhaus) [inline src/controllers/hid/hidcontroller.cpp]: - Please put this at the top of the file (below includes/forward declarations)
- I think a regular `int` suffices
- Name it `kSizeOfReportID`
- No newline before the opening brace

**Review by Holzhaus — CHANGES_REQUESTED** [review]

File: src/controllers/hid/hidcontroller.cpp (hunk 19 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: Done

File: src/controllers/hid/hidcontroller.cpp (hunk 15 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: 512 replaced by a constexpr now

**Review by Holzhaus — APPROVED** [review]
Code LGTM, unfortunately I can't test this as I don't own an HID controller.

**Comment by JoergAtGithub** [comment]
@ywwg Hello Owen, can this be merged?

**Comment by Holzhaus** [comment]
Ping @ywwg

**Comment by JoergAtGithub** [comment]
What can I do, to get this PR merged?

**Comment by JoergAtGithub** [comment]
@ywwg Do you've any objections to merge this?

**Comment by uklotzde** [comment]
Ping @ywwg

File: src/controllers/hid/hidcontroller.cpp [hunk 20]
```diff
@@ -20,6 +20,11 @@ ControllerJSProxy* HidController::jsProxy() {
     return new HidControllerJSProxy(this);
 }
 
+namespace {
+constexpr int kReportIdSize = 1;             // Size of an USB HID Report ID is always one byte
+constexpr int kMaxHidErrorMessageSize = 512; // Maximum size of an HID error message string
```
Comment (ywwg) [inline src/controllers/hid/hidcontroller.cpp:25]: comment is redundant, constant name is clear

**Review by ywwg — APPROVED** [review]
this looks straightforward.  It would be nice if there was a way to add a test for this but we don't have any tests for hidcontroller :(

LGTM

**Comment by ywwg** [comment]
sorry for my lack of response, github notifies me about every single PR and doesn't highlight individual pings :/.  Best to @ me on zulip to get my attention

File: src/controllers/hid/hidcontroller.cpp (hunk 20 above)
Comment (JoergAtGithub) [reply src/controllers/hid/hidcontroller.cpp]: I removd the comment lines

**Comment by Holzhaus** [comment]
> github notifies me about every single PR and doesn't highlight individual pings :/

Btw, GitHub does show if you've been mentioned at least once in the PR, but it not obvious:

Screenshot_20201002_221104

It's probably still better to ping people on Zulip.

**Comment by JoergAtGithub** [comment]
Merge?

**Comment by uklotzde** [comment]
Safe to merge and after everyone approved the PR no reason for holding this back any longer. Thank your for contributing to Mixxx, Jörg. LGTM
