### PR TITLE
Fix build with GCC 5.4

### PR DESCRIPTION
**Pull request by ninomp**

### CODE REVIEW

**Comment by rryan** [comment]
Thanks! This breaks the macOS build. You probably need an `#include <cmath>` at the top.

```
src/effects/lv2/lv2manifest.cpp:125:22: error: expected unqualified-id
            if (std::isnan(m_default[i])) {
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:179:5: note: expanded from macro 'isnan'
    ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
    ^
src/effects/lv2/lv2manifest.cpp:131:22: error: expected unqualified-id
            if (std::isnan(m_minimum[i])) {
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:179:5: note: expanded from macro 'isnan'
    ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
    ^
src/effects/lv2/lv2manifest.cpp:137:22: error: expected unqualified-id
            if (std::isnan(m_maximum[i])) {
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:179:5: note: expanded from macro 'isnan'
    ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
    ^
```

**Comment by rryan** [comment]
Er, please use 
```
#include "util/math.h"
```
instead

**Comment by ninomp** [comment]
I made the change. Let's see if this will work. Btw, should I squash this two commits into one?

**Comment by daschuer** [comment]
Thank you. No need to squash. LGTM
