### PR TITLE
QML: Add support for selecting/loading effects

### PR DESCRIPTION
**Pull request by Holzhaus**
Based on #3992.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Please Rebase.

Also PR nr 4000. Yeah :tada:

**Comment by Holzhaus** [comment]
Caveeats: The comboboxes currently don't have any signal connections the actual effect slot. This means changing the effects from the controller or via COs won't work atm.

File: res/skins/QMLDemo/EffectUnit.qml [hunk 1]
```diff
@@ -53,7 +57,12 @@ Item {
                     anchors.right: effectMetaKnob.left
                     anchors.margins: 5
                     // TODO: Add a way to retrieve effect names here
-                    model: ["---", "Effect 1", "Effect 2", "Effect 3", "Effect 4"]
+                    textRole: "display"
+                    model: Mixxx.EffectsManager.visibleEffectsModel
+                    onActivated: {
+                        console.warn(1, root.unitNumber, effect.effectNumber, model.get(index).effectId);
+                        Mixxx.EffectsManager.loadEffect(1, root.unitNumber, effect.effectNumber, model.get(index).effectId);
```
Comment (Swiftb0y) [inline res/skins/QMLDemo/EffectUnit.qml:64]: I'm not sure I like this... Though I don't really have anything better to propose...

**Review by Swiftb0y — COMMENTED** [review]
I really can't comment on any C++ changes. Though the current approach seems a bit clunky to me.

**Comment by Swiftb0y** [comment]
Clicking outside the Combobox popup doesn't close it for some reason. I need to click on another interactive element such as a Button or Knob. It would also be great if the combobox was editable and you could just search for the effect you wanted in the model, but thats polish to be done later.

File: src/skin/qml/qmlvisibleeffectsmodel.h [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+#include "effects/effectsmanager.h"
+
+namespace mixxx {
+namespace skin {
+namespace qml {
+
+class QmlVisibleEffectsModel : public QAbstractListModel {
+    Q_OBJECT
+  public:
+    enum Roles {
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply src/skin/qml/qmlvisibleeffectsmodel.h:14]: It works, but it's kind of clunky because of all the casting between int and the enum value. Since the enum part of the class body and each member has a "Role" suffix, I think it's okay like this.

@uklotzde opinions?

File: res/skins/QMLDemo/EffectUnit.qml (hunk 1 above)
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectUnit.qml:64]: The question is how do we receive changes. I checked the controls and didn't see any COs that indicate the currently loaded effect. Therefore I think we need to add a QmlEffectChainSlotProxy that can emit signals when the effect is changed. If we do that, we can move the load method there.

Comment (Swiftb0y) [reply res/skins/QMLDemo/EffectUnit.qml:64]: Binding to (`EffectRack1_EffectUnitN_EffectM`,`loaded`) might work. It should emit a "trigger" signal even if the value didn't change. But in the long term, we do need `QmlEffectChainSlotProxy` anyways so we can configure the parameters and so forth. We might even consider trying to remove the GUI changes from #2618 and redo that part based on QML.

Comment (Holzhaus) [reply res/skins/QMLDemo/EffectUnit.qml:64]: I don't think we actually need it for parameter configuration except the names.

Comment (Swiftb0y) [reply res/skins/QMLDemo/EffectUnit.qml:64]: Well we don't really need it, but I find the current way its implemented with COs very hacky and would like to get rid of it in the longterm actually..

**Comment by Holzhaus** [comment]
I agree, but on the other hand I don't know if it's possible to expose stuff like that with making `EffectsManager` a singleton which I dislike even more.

**Review by Swiftb0y — APPROVED** [review]
Not super happy with the QML but its fine as a short term solution. I'd prefer if someone with more C++ experience would take a look at that though before merging.

**Comment by Holzhaus** [comment]
I also added initial support for expandable effect units. Don't pay too much attention to that, it's not that useful yet because there is no support for effect parameter names, linking or other fancy stuff yet.

I'll probably have to refactor it later on by implementing a `QmlEffectParametersModel` that is used by a `ListView`. It'll take care of that in a separate PR.

**Comment by Holzhaus** [comment]
Nevermind, switched to the listmodel approach in this PR.

File: res/skins/QMLDemo/EffectUnit.qml [hunk 3]
```diff
@@ -1,75 +1,109 @@
 import "." as Skin
+import Mixxx 0.1 as Mixxx
 import QtQuick 2.12
 import QtQuick.Controls 2.12
 import QtQuick.Layouts 1.12
 import "Theme"
 
 Item {
```
Comment (Swiftb0y) [inline res/skins/QMLDemo/EffectUnit.qml:8]: not sure if you think the effort is worth it, but you could add the expanded controls from latenight as well: 
image

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+QHash<int, QByteArray> QmlEffectManifestParametersModel::roleNames() const {
+    return kRoleNames;
+}
+
+QVariant QmlEffectManifestParametersModel::get(int row) const {
+    QModelIndex idx = index(row, 0);
+    QVariantMap dataMap;
+    for (auto it = kRoleNames.constBegin(); it != kRoleNames.constEnd(); it++) {
+        dataMap.insert(it.value(), data(idx, it.key()));
+    }
```
Comment (Swiftb0y) [inline src/skin/qml/qmleffectmanifestparametersmodel.cpp:67]: use `std::for_each` or Qt `foreach` macro?

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    case QmlEffectManifestParametersModel::IdRole:
+        return pParameter->id();
+    case QmlEffectManifestParametersModel::NameRole:
+        return pParameter->name();
+    case QmlEffectManifestParametersModel::ShortNameRole:
+        return pParameter->shortName();
+    case QmlEffectManifestParametersModel::DescriptionRole:
+        return pParameter->description();
+    case QmlEffectManifestParametersModel::ControlHintRole:
+        return static_cast<int>(pParameter->controlHint());
```
Comment (Swiftb0y) [inline src/skin/qml/qmleffectmanifestparametersmodel.cpp:43]: Can't we expose the enum directly?

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    default:
+        return QVariant();
+    }
+}
+
+int QmlEffectManifestParametersModel::rowCount(const QModelIndex& parent) const {
+    if (parent.isValid()) {
+        return 0;
+    }
```
Comment (Swiftb0y) [inline src/skin/qml/qmleffectmanifestparametersmodel.cpp:52]:
```suggestion
    if (!parent.isValid()) {
        return 0;
    }
```
not sure how the QModelIndex API is used, but returning early when the parent is valid seems strange.

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
The size of the line indicator seems too big. 
image

File: res/skins/QMLDemo/EffectRow.qml [hunk 7]
```diff
@@ -2,25 +2,43 @@ import "." as Skin
...
+        }
 
-        width: root.width / 2
-        height: root.height
-        unitNumber: 1
     }
 
-    Skin.EffectUnit {
-        id: effectUnit2
+    Skin.SectionBackground {
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectRow.qml:30]: No. EffectUnits vary in height, depending on whether they're expanded or not. The special case here is that both backgrounds need to have the same height as the *highest* effect unit. I found that very complicated to solve in another way. If you have a better idea, feel free to open a follow-up PR.

File: res/skins/QMLDemo/EffectSlot.qml [hunk 8]
```diff
@@ -0,0 +1,196 @@
+import "." as Skin
+import Mixxx 0.1 as Mixxx
+import QtQuick 2.12
+import "Theme"
+
+Item {
+    id: root
+
+    property var slot: Mixxx.EffectsManager.getEffectSlot(1, unitNumber, effectNumber)
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:9]: Didn't work when I tried, then I read that it is not possible to use uncreatable types as property types. But according to this bug report it should be fixed since Qt 5.8: https://bugreports.qt.io/browse/QTBUG-36752 I'll check again.

File: res/skins/QMLDemo/EffectSlot.qml [hunk 9]
```diff
@@ -0,0 +1,196 @@
...
+    property int unitNumber // required
+    property int effectNumber // required
+    property bool expanded: false
+    readonly property string group: slot.group
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:13]: Didn't try, maybe the readonly flag from the slot property is also applying to the alias. I can check.

File: res/skins/QMLDemo/EffectSlot.qml [hunk 10]
```diff
@@ -0,0 +1,196 @@
...
+        Skin.ComboBox {
+            id: effectSelector
+
+            anchors.top: parent.top
+            anchors.bottom: parent.bottom
+            anchors.left: effectEnableButton.right
+            anchors.right: effectMetaKnob.left
+            anchors.margins: 5
+            // TODO: Add a way to retrieve effect names here
+            textRole: "display"
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:50]: Nope :D

File: res/skins/QMLDemo/EffectSlot.qml [hunk 11]
```diff
@@ -0,0 +1,196 @@
...
+            model: Mixxx.EffectsManager.visibleEffectsModel
+            onActivated: {
+                const effectId = model.get(index).effectId;
+                if (root.slot.effectId != effectId)
+                    root.slot.effectId = effectId;
+
+            }
+            Component.onCompleted: root.slot.onEffectIdChanged()
+
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:59]: This makes sure the combobox shows the effect name after starting mixxx (Mixxx remembers effects persistently). Otherwise the effect slot look empty even though it's not.

File: res/skins/QMLDemo/EffectUnit.qml (hunk 3 above)
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectUnit.qml:8]: This PR is already quite big. Someone can take care of that separately I think. There's also other stuff missing, like the link type, or configuring the knob arc start from the parameter, etc.

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp (hunk 4 above)
Comment (Holzhaus) [reply src/skin/qml/qmleffectmanifestparametersmodel.cpp:67]: AFAIK that would only iterate over the keys, not the values: https://doc.qt.io/qt-5/qhash.html#details (search page for `foreach`).

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp (hunk 5 above)
Comment (Holzhaus) [reply src/skin/qml/qmleffectmanifestparametersmodel.cpp:43]: Unsure. In the end this would be better, but the enum doesn't conform to our naming standard anyway. I would change that, but I really don't want to cause more conflicts with #2618. I can add a TODO comment to take care of that after that PR has been merged.

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp (hunk 6 above)
Comment (Holzhaus) [reply src/skin/qml/qmleffectmanifestparametersmodel.cpp:52]: This model is a *list*. This means it has N rows. If *parent* is valid, this means that we're not requesting the rowCount for the whole list, but for an individual *item*. If this was a tree model (like the library sidebar), then each item might also have children. This is not the case here. Therefore, we always return zero, because no item has children.

File: res/skins/QMLDemo/EffectRow.qml (hunk 7 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply res/skins/QMLDemo/EffectRow.qml:30]: I understand.

File: res/skins/QMLDemo/EffectSlot.qml [hunk 12]
```diff
@@ -0,0 +1,196 @@
...
+                color: Theme.effectColor
+                visible: parameter.isKnob
+
+                Mixxx.ControlProxy {
+                    id: parameterLoadedControl
+
+                    property bool loaded: value != 0
+
+                    group: root.group
+                    key: "parameter" + parameter.number + "_loaded"
```
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:144]: Interesting, didn't know this was possible. I'll check if it works.

File: src/skin/qml/qmleffectmanifestparametersmodel.cpp (hunk 6 above)
Comment (Swiftb0y) [reply src/skin/qml/qmleffectmanifestparametersmodel.cpp:52]: I understand now. Thanks for the explanation. I guess I should read the Qt docs first without asking questions in code review.

File: res/skins/QMLDemo/EffectSlot.qml (hunk 9 above)
[the remark this answers is not in the document]
Comment (Holzhaus) [reply res/skins/QMLDemo/EffectSlot.qml:13]: Nope, doesn't work. Maybe because the order of property initializiation is not defined or something:

```
warning [Main] file:///home/jan/Projects/mixxx/res/skins/QMLDemo/main.qml:120:9: Type EffectRow unavailable
             EffectRow {
             ^
warning [Main] file:///home/jan/Projects/mixxx/res/skins/QMLDemo/EffectRow.qml:14:9: Type Skin.EffectUnit unavailable
             Skin.EffectUnit {
             ^
warning [Main] file:///home/jan/Projects/mixxx/res/skins/QMLDemo/EffectUnit.qml:24:9: Type EffectSlot unavailable
             EffectSlot {
             ^
warning [Main] file:///home/jan/Projects/mixxx/res/skins/QMLDemo/EffectSlot.qml:13:27: Invalid alias reference. Unable to find id "slot"
         property alias group: slot.group
                               ^
warning [Main] Skin "QMLDemo" failed to load!
```

[the remark this answers is not in the document]
Comment (Swiftb0y) [reply res/skins/QMLDemo/EffectSlot.qml:13]: Mhmm thats strange. I guess I'm misinterpreting the Qt docs section https://doc.qt.io/qt-5/qtqml-syntax-objectattributes.html#considerations-for-property-aliases

File: res/skins/QMLDemo/EffectSlot.qml [hunk 13]
```diff
@@ -109,17 +108,17 @@ Item {
             id: parameter
 
             property int number: index + 1
-            property string name: shortName
+            property string label: shortName ? shortName : name
```
Comment (Swiftb0y) [inline res/skins/QMLDemo/EffectSlot.qml:111]: can you add a comment that indicates that nullish coalescing (so `shortName ?? name`) will also work for Qt5.15?

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
Thanks. Unfortunately there are still two blocking issues IMO. 
1. The effectUnit desperately needs a DryWet knob, otherwise the unit stays inaudible when mixxx started completely dry. 
2. The buttons for the parameters of a effect don't actually work atm. You can most easily test this using the Tremolo Effect and playing with the Quantize and Triplet buttons.

**Comment by Holzhaus** [comment]
> Thanks. Unfortunately there are still two blocking issues IMO.
> 
> 1. The effectUnit desperately needs a DryWet knob, otherwise the unit stays inaudible when mixxx started completely dry.

I don't consider this a blocker, but I added it. Only visible when expanded though.

> 2. The buttons for the parameters of a effect don't actually work atm. You can most easily test this using the Tremolo Effect and playing with the Quantize and Triplet buttons.

I checked, and some buttons did work, some did not, because our effect CO infrastructure is badly designed IMHO. I tried to mitigate this by adding a way to retrieve the parameter control key from the model.

**Review by Swiftb0y — APPROVED** [review]
> I checked, and some buttons did work, some did not, because our effect CO infrastructure is badly designed IMHO. I tried to mitigate this by adding a way to retrieve the parameter control key from the model.

Thats very strange I'll guess we should take care of it in conjunction with #2618.

LGTM. I guess no one else is interested in reviewing this so I'm just going to merge now.

**Comment by ywwg** [comment]
This merge seems to have made mixxx unbuildable at HEAD for me:

```
/usr/bin/ld: libmixxx-lib.a(mocs_compilation.cpp.o): in function `mixxx::skin::qml::QmlEffectsManagerProxy::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
mocs_compilation.cpp:(.text+0x9a4): undefined reference to `mixxx::skin::qml::QmlEffectsManagerProxy::getEffectSlot(int, int, int) const'
/usr/bin/ld: libmixxx-lib.a(mocs_compilation.cpp.o): in function `mixxx::skin::qml::QmlVisibleEffectsModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
mocs_compilation.cpp:(.text+0xa8d): undefined reference to `mixxx::skin::qml::QmlVisibleEffectsModel::get(int) const'
/usr/bin/ld: libmixxx-lib.a(mocs_compilation.cpp.o): in function `mixxx::skin::qml::QmlEffectManifestParametersModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
mocs_compilation.cpp:(.text+0xb6f): undefined reference to `mixxx::skin::qml::QmlEffectManifestParametersModel::get(int) const'
/usr/bin/ld: libmixxx-lib.a(mocs_compilation.cpp.o): in function `mixxx::skin::qml::QmlEffectSlotProxy::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
mocs_compilation.cpp:(.text+0xe7a): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getEffectId() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xeca): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getGroup() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xed1): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getNumber() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xeea): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getChainSlotGroup() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xef1): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getChainSlotNumber() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xf0a): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getRackGroup() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xf19): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getRackNumber() const'
/usr/bin/ld: mocs_compilation.cpp:(.text+0xf29): undefined reference to `mixxx::skin::qml::QmlEffectSlotProxy::getParametersModel() const'```

Bisecting identifies the first bad commit as: 8cab62323a5dc45a32e45378c0ceca25a3eba630

At first glance I have no idea why.

**Comment by ywwg** [comment]
Cleaning out cbuild seems to fix it
