### ISSUE TITLE
Numark Mixtrack Pro 3: script tried to connect to ControlObject ([Sampler5], play) which is non-existent

### ISSUE THREAD

**Issue by eiglow** [mixxxdj/mixxx#12808]
### Bug Description

This error occurs on startup. It seems to cause my controller to not work, because along with the error, it says "The functionality provided by this controller mapping will be disabled until the issue has been resolved."

```
Uncaught exception: file:///usr/share/mixxx/controllers/Numark-Mixtrack-3-scripts.js:814: Error: script tried to connect to ControlObject ([Sampler5], play) which is non-existent.
Backtrace: @file:///usr/share/mixxx/controllers/Numark-Mixtrack-3-scripts.js:814
@file:///usr/share/mixxx/controllers/Numark-Mixtrack-3-scripts.js:894
```

The error only seems to have started occurring after my last update, so it may be from a recent change. I'll edit the ticket if I find out more info for a known good version.

### Version

2.4.0-beta (git d112e4c)

### OS

Fedora 40 (rawhide)

**Comment by ronso0** [comment]
Thank you for reporting this bug!

The commit causing this regression is reverted in #12809
