### PR TITLE
SoundSourceM4A: Fix armv7hl build on gcc 11.1 

### PR DESCRIPTION
**Pull request by uklotzde**
Next build error: https://koji.rpmfusion.org/kojifiles/work/tasks/9223/489223/build.log

```
-Werror -fPIC -pthread -std=gnu++17 -MD -MT CMakeFiles/mixxx-lib.dir/src/sources/soundsourcem4a.cpp.o -MF CMakeFiles/mixxx-lib.dir/src/sources/soundsourcem4a.cpp.o.d -o CMakeFiles/mixxx-lib.dir/src/sources/soundsourcem4a.cpp.o -c ../src/sources/soundsourcem4a.cpp
In file included from ../src/audio/types.h:7,
                 from ../src/audio/signalinfo.h:3,
                 from ../src/audio/streaminfo.h:3,
                 from ../src/sources/audiosource.h:3,
                 from ../src/sources/soundsource.h:5,
                 from ../src/sources/soundsourcem4a.h:3,
                 from ../src/sources/soundsourcem4a.cpp:1:
../src/sources/soundsourcem4a.cpp: In member function 'virtual mixxx::ReadableSampleFrames mixxx::SoundSourceM4A::readSampleFramesClamped(const mixxx::WritableSampleFrames&)':
../src/sources/soundsourcem4a.cpp:770:68: error: comparison of integer expressions of different signedness: 'mixxx::audio::SampleRate::value_t' {aka 'unsigned int'} and 'SINT' {aka 'int'} [-Werror=sign-compare]
  770 |             VERIFY_OR_DEBUG_ASSERT(getSignalInfo().getSampleRate() ==
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  771 |                     SINT(decFrameInfo.samplerate)) {
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   
../src/util/assert.h:62:45: note: in definition of macro 'VERIFY_OR_DEBUG_ASSERT'
   62 | #define VERIFY_OR_DEBUG_ASSERT(cond) if ((!(cond)) && mixxx_maybe_debug_assert_return_true(#cond, __FILE__, __LINE__, ASSERT_FUNCTION))
      |                                             ^~~~
cc1plus: all warnings being treated as errors
```

### CODE REVIEW

**Comment by uklotzde** [comment]
Needed for the next build roundtrip which takes hours.

**Comment by uklotzde** [comment]
Ping. Otherwise I will merge myself.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Sorry nobody else got to it sooner.

**Comment by Swiftb0y** [comment]
I'm no C++ expert but I guess it'll work since there were no build errors and I wasn't able to identify issues by looking at the code...

**Comment by uklotzde** [comment]
Thanks for merging. The changes are almost trivial, type shuffling. We only need a quick review here to prevent that mistakes slip through unnoticed if they are not detected by tests.
